import Link from "next/link";
import { ResourceAreaShell } from "@/components/resource-area-shell";

export default function ResourceLabPage() {
  return <ResourceAreaShell title="Laboratorio esercizi ARMONIA" description="Un futuro spazio per costruire attività e compiti a casa collegabili al lavoro terapeutico, senza appesantire la gestione quotidiana." icon="◇" tone="bg-violet-50 text-violet-700">
    <div className="mt-8 flex flex-wrap items-center gap-2 text-sm font-bold text-slate-600" aria-label="Flusso futuro del laboratorio">
      {['Mattoncini', 'Ricette', 'Esercizi', 'Compiti a casa'].map((label, index) => <div className="contents" key={label}>{index > 0 && <span className="text-slate-300" aria-hidden="true">→</span>}<span className="rounded-full border border-violet-100 bg-violet-50/70 px-3 py-2">{label}</span></div>)}
    </div>
    <div className="mt-8 rounded-[1.5rem] border border-violet-200 bg-violet-50/60 p-5"><p className="text-sm font-bold text-violet-900">Tre mattoncini pilota disponibili</p><p className="mt-1 text-sm leading-6 text-slate-600">Prova denominazione da immagine, coppie minime e ripetizione parole/non-parole in una preview senza salvataggio.</p><Link href="/risorse/laboratorio/crea" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-violet-700 px-4 text-sm font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400">Crea attività →</Link></div>
    <div className="mt-8 border-t border-violet-100 pt-6"><p className="text-sm font-bold">Fondazioni editoriali</p><p className="mt-1 text-sm leading-6 text-slate-500">La Banca Asset raccoglie le rappresentazioni visive; la Banca Contenuti descrive le unità linguistiche riutilizzabili. Nessuna delle due genera ancora esercizi.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/risorse/laboratorio/banca" className="inline-flex min-h-11 items-center rounded-xl bg-violet-100 px-4 text-sm font-bold text-violet-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400">Apri Banca Asset →</Link><Link href="/risorse/laboratorio/contenuti" className="inline-flex min-h-11 items-center rounded-xl border border-violet-200 bg-white px-4 text-sm font-bold text-violet-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400">Apri Banca Contenuti →</Link></div></div>
  </ResourceAreaShell>;
}
