import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "ARMONIA — Gestionale per logopedisti",
  description: "Agenda, pazienti, percorso clinico, strumenti, materiali ed economia in uno spazio di lavoro progettato per logopedisti.",
  alternates: { canonical: "https://conarmonia.it" },
  openGraph: { title: "ARMONIA — Gestionale per logopedisti", description: "Il lavoro quotidiano del logopedista, finalmente nello stesso spazio.", url: "https://conarmonia.it", siteName: "ARMONIA", locale: "it_IT", type: "website" },
};

const Arrow = () => <svg aria-hidden="true" viewBox="0 0 20 20" className="h-4 w-4 fill-none stroke-current stroke-2"><path d="M4 10h12m-5-5 5 5-5 5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
const Check = () => <svg aria-hidden="true" viewBox="0 0 20 20" className="h-4 w-4 fill-none stroke-current stroke-2"><path d="m4 10 4 4 8-9" strokeLinecap="round" strokeLinejoin="round" /></svg>;

function Brand() {
  return <Link href="/" className="inline-flex min-h-11 items-center gap-2.5 rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500 focus-visible:ring-offset-4"><Image src="/branding/logo-mark.svg" alt="" width={34} height={38} priority className="h-9 w-8 object-contain" /><span className="text-[15px] font-bold tracking-[.2em] text-[#264c38]">ARMONIA</span></Link>;
}

function ProductMockup() {
  return <div className="landing-float relative mx-auto w-full max-w-[660px]" aria-label="Anteprima illustrativa dell’interfaccia ARMONIA">
    <div className="absolute -inset-6 -z-10 rounded-[3rem] bg-[radial-gradient(circle_at_40%_30%,rgba(152,181,137,.3),transparent_64%)] blur-2xl" />
    <div className="overflow-hidden rounded-[1.7rem] border border-white/80 bg-white/95 shadow-[0_32px_90px_rgba(34,65,48,.2)] ring-1 ring-[#dce8dc]">
      <div className="flex h-9 items-center gap-1.5 border-b border-[#e8eee7] bg-[#f9fbf8] px-4"><span className="h-2 w-2 rounded-full bg-[#d9aaa0]"/><span className="h-2 w-2 rounded-full bg-[#e6cc8b]"/><span className="h-2 w-2 rounded-full bg-[#92b08d]"/><span className="ml-3 text-[9px] font-bold tracking-[.14em] text-[#7c8b82]">SPAZIO CLINICO</span></div>
      <div className="grid min-h-[390px] grid-cols-[74px_1fr] sm:grid-cols-[116px_1fr]">
        <aside className="border-r border-[#e7ede6] bg-[#f3f7f1] p-3 sm:p-4"><div className="flex items-center gap-2"><Image src="/branding/logo-mark.svg" alt="" width={22} height={24} className="h-6 w-5"/><span className="hidden text-[9px] font-extrabold tracking-[.14em] text-[#41644b] sm:inline">ARMONIA</span></div><div className="mt-8 space-y-2">{["Oggi","Pazienti","Calendario","Risorse"].map((item,index)=><div key={item} className={`rounded-lg px-2 py-2 text-[8px] font-bold sm:text-[10px] ${index===1?"bg-[#dfeade] text-[#365840]":"text-[#89958e]"}`}>{item}</div>)}</div></aside>
        <div className="min-w-0 bg-[#fbfcfa] p-4 sm:p-6">
          <div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#7c8c82]">Paziente</p><h3 className="mt-1 text-base font-bold text-[#24352f] sm:text-xl">Percorso clinico</h3><p className="mt-1 text-[10px] text-[#7a8780]">Una visione continua, senza passaggi rigidi</p></div><span className="rounded-full bg-[#e4efe1] px-2 py-1 text-[8px] font-bold text-[#46654c]">Attivo</span></div>
          <div className="mt-5 grid gap-3 sm:grid-cols-[1.45fr_.8fr]">
            <div className="rounded-2xl border border-[#e1e9df] bg-white p-4 shadow-[0_8px_22px_rgba(43,69,55,.05)]"><div className="flex items-center justify-between"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#718078]">Continuità del percorso</p><span className="text-[9px] text-[#77857d]">Oggi</span></div><div className="mt-4 space-y-4 border-l border-[#cddcca] pl-4"><div className="relative"><span className="absolute -left-[21px] top-1 h-2.5 w-2.5 rounded-full bg-[#628269] ring-4 ring-[#edf4eb]"/><p className="text-[10px] font-bold">Seduta registrata</p><p className="mt-1 text-[9px] text-[#7a8780]">Obiettivo e materiali collegati</p></div><div className="relative"><span className="absolute -left-[21px] top-1 h-2.5 w-2.5 rounded-full bg-[#b7c9b2] ring-4 ring-[#f1f5ef]"/><p className="text-[10px] font-bold">Valutazione</p><p className="mt-1 text-[9px] text-[#7a8780]">Profilo linguistico aggiornato</p></div><div className="rounded-xl bg-[#f2f6f0] p-3"><p className="text-[9px] font-bold text-[#46654c]">Obiettivo terapeutico</p><p className="mt-1 text-[9px] leading-4 text-[#66756c]">Generalizzazione nella comunicazione quotidiana</p></div></div></div>
            <div className="space-y-3"><div className="rounded-2xl bg-[#345b45] p-4 text-white"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-white/65">Prossimo</p><p className="mt-3 text-sm font-bold">09:30 · Seduta</p><p className="mt-1 text-[9px] text-white/70">Studio · 45 minuti</p><span className="mt-4 inline-flex rounded-full bg-white/10 px-2 py-1 text-[8px] font-bold">Agenda</span></div><div className="rounded-2xl border border-[#e2e9e0] bg-white p-4"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#7b887f]">Risorse</p><div className="mt-3 flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f1e8df] text-[10px] font-bold text-[#866a58]">PDF</span><div><p className="text-[9px] font-bold">Scheda paziente</p><p className="text-[8px] text-[#87938c]">Pronta per la seduta</p></div></div></div></div>
          </div>
        </div>
      </div>
    </div>
    <div className="absolute -bottom-5 -left-3 hidden rounded-2xl border border-white bg-white/95 px-4 py-3 shadow-xl sm:block"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#7d8a82]">Seduta</p><p className="mt-1 text-xs font-bold text-[#345b45]">Registrata correttamente</p></div>
  </div>;
}

function ClinicalVisual() { return <div className="mt-7 rounded-2xl border border-[#dce7da] bg-[#f8faf7] p-4"><div className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-4">{[["01","Valutazione","Profilo linguistico"],["02","Obiettivi","Priorità del percorso"],["03","Sedute","Continuità e follow-up"]].map(([n,title,note],i)=><div className="contents" key={n}><span className={`grid h-7 w-7 place-items-center rounded-full text-[9px] font-bold ${i===0?"bg-[#46654c] text-white":"border border-[#bfd0bb] bg-white text-[#46654c]"}`}>{n}</span><div className={i<2?"border-b border-[#e0e8de] pb-3":""}><p className="text-xs font-bold">{title}</p><p className="mt-0.5 text-[10px] text-slate-500">{note}</p></div></div>)}</div></div>; }
function AgendaVisual() { return <div className="mt-6 grid grid-cols-3 gap-2">{["Lun 12","Mar 13","Mer 14"].map((d,i)=><div key={d} className={`rounded-xl border p-2 ${i===1?"border-[#9db598] bg-[#edf4eb]":"border-[#e4eae2] bg-white"}`}><p className="text-[9px] font-bold text-slate-500">{d}</p><div className={`mt-3 h-12 rounded-lg ${i===0?"bg-[#e8dded]":i===1?"bg-[#d5e5d2]":"bg-[#f2e1d6]"}`}><span className="block px-2 pt-2 text-[8px] font-bold text-[#52665a]">{i===1?"Seduta ✓":"Appuntamento"}</span></div></div>)}</div>; }
function LabVisual() { return <div className="mt-6 grid grid-cols-2 gap-2">{["Denominazione","Coppie minime","Lettura","Attività multiple"].map((x,i)=><div key={x} className={`rounded-xl border border-[#e2e8df] p-3 ${i===3?"bg-[#e9f1e7]":"bg-white"}`}><span className="block h-1.5 w-8 rounded-full bg-[#94ad90]"/><p className="mt-3 text-[9px] font-bold text-[#43564b]">{x}</p></div>)}</div>; }
function FeatureCard({className="",eyebrow,title,copy,children}:{className?:string;eyebrow:string;title:string;copy:string;children:React.ReactNode}) { return <article className={`landing-card group rounded-[1.6rem] border border-[#dfe8dc] bg-white p-5 shadow-[0_16px_45px_rgba(43,69,55,.055)] sm:p-7 ${className}`}><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#67806c]">{eyebrow}</p><h3 className="mt-2 text-xl font-bold tracking-tight text-[#23372c] sm:text-2xl">{title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-[#68766e]">{copy}</p>{children}</article>; }

export default function HomePage() {
  return <main className="landing-page min-h-screen bg-[#f8faf6] text-[#24352f]">
    <header className="sticky top-0 z-30 border-b border-[#e6ece3]/90 bg-[#f8faf6]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1240px] items-center justify-between px-4 py-3 sm:px-6 lg:px-8"><Brand/><nav aria-label="Navigazione principale" className="hidden items-center gap-7 md:flex"><a href="#funzioni" className="rounded-md text-sm font-semibold text-[#607067] hover:text-[#31553d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Funzioni</a><a href="#perche-armonia" className="rounded-md text-sm font-semibold text-[#607067] hover:text-[#31553d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Perché ARMONIA</a></nav><div className="flex items-center gap-2"><Link href="/login" className="inline-flex min-h-11 items-center rounded-xl px-3 text-sm font-bold text-[#46654c] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Accedi</Link><Link href="/signup" className="hidden min-h-11 items-center rounded-xl bg-[#315d43] px-4 text-sm font-bold text-white shadow-sm hover:bg-[#274d37] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500 focus-visible:ring-offset-2 sm:inline-flex">Crea account</Link></div></div></header>
    <section className="relative overflow-hidden"><div className="landing-orb absolute right-[-12rem] top-10 h-[32rem] w-[32rem] rounded-full bg-[#dfeadc]/55 blur-3xl"/><div className="mx-auto grid max-w-[1240px] gap-14 px-4 pb-24 pt-16 sm:px-6 sm:pt-24 lg:grid-cols-[.86fr_1.14fr] lg:items-center lg:px-8 lg:pb-32 lg:pt-28"><div className="relative z-10"><p className="inline-flex rounded-full border border-[#cbdac7] bg-white/70 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.17em] text-[#46654c]">ARMONIA · Gestionale per logopedisti</p><h1 className="mt-7 max-w-[680px] text-[2.7rem] font-bold leading-[1.02] tracking-[-.045em] text-[#20372b] sm:text-6xl lg:text-[4rem]">Il lavoro del logopedista,<br/><span className="text-[#52745a]">finalmente nello stesso spazio.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-[#617168] sm:text-lg">Agenda, pazienti, percorso clinico, strumenti, materiali ed economia. ARMONIA riunisce il lavoro quotidiano senza trasformarlo in una checklist.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#315d43] px-6 font-bold text-white shadow-[0_12px_28px_rgba(49,93,67,.2)] transition hover:-translate-y-0.5 hover:bg-[#274d37] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500 focus-visible:ring-offset-2">Crea account <Arrow/></Link><Link href="/login" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-[#cbd9c8] bg-white px-6 font-bold text-[#3e6249] transition hover:-translate-y-0.5 hover:bg-[#f2f7f0] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Accedi</Link></div><a href="#funzioni" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg text-sm font-bold text-[#5f7565] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Scopri ARMONIA <span aria-hidden="true">↓</span></a></div><ProductMockup/></div></section>
    <section id="perche-armonia" className="border-y border-[#dfe7dd] bg-white"><div className="mx-auto grid max-w-[1120px] gap-7 px-4 py-20 sm:px-6 md:grid-cols-[.8fr_1.2fr] md:items-end lg:px-8"><h2 className="text-4xl font-bold leading-tight tracking-[-.04em] text-[#23392d] sm:text-5xl">Semplice fuori.<br/><span className="text-[#6d8a72]">Profonda dentro.</span></h2><div><p className="max-w-2xl text-lg leading-8 text-[#607067]">ARMONIA mette in primo piano ciò che serve oggi e lascia il dettaglio disponibile quando serve: una panoramica rapida, un percorso clinico leggibile e nessuna checklist rigida imposta al professionista.</p><div className="mt-6 flex flex-wrap gap-2">{["Panoramica immediata","Dettaglio facoltativo","Continuità clinica"].map(x=><span key={x} className="rounded-full bg-[#f0f5ee] px-3 py-2 text-xs font-bold text-[#506c56]">{x}</span>)}</div></div></div></section>
    <section id="funzioni" className="mx-auto max-w-[1240px] px-4 py-24 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#66806c]">Un unico spazio di lavoro</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] sm:text-5xl">Ogni parte parla con le altre.</h2><p className="mt-4 text-base leading-7 text-[#66756d]">Dal primo appuntamento alla documentazione professionale, senza perdere il filo del percorso.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-12">
      <FeatureCard className="lg:col-span-7 lg:row-span-2" eyebrow="Percorso clinico" title="Il quadro clinico resta leggibile" copy="Valutazioni, obiettivi e continuità del percorso senza ridurre il lavoro clinico a una checklist."><ClinicalVisual/></FeatureCard>
      <FeatureCard className="lg:col-span-5" eyebrow="Agenda e sedute" title="Dall’appuntamento alla seduta" copy="Appuntamenti, ricorrenze e sedute nello stesso flusso."><AgendaVisual/></FeatureCard>
      <FeatureCard className="lg:col-span-5" eyebrow="Laboratorio" title="Attività che diventano schede" copy="Costruisci attività, schede e compiti da assegnare al paziente."><LabVisual/></FeatureCard>
      <FeatureCard className="lg:col-span-4" eyebrow="Strumenti clinici" title="Professionali e contestuali" copy="Strumenti professionali, integrazioni native e risorse originali ARMONIA."><div className="mt-6 space-y-2"><div className="flex items-center justify-between rounded-xl bg-[#f2f6f0] p-3 text-xs font-bold"><span>Italian QAB</span><span className="rounded-full bg-[#dbe9d8] px-2 py-1 text-[9px] text-[#46654c]">Integrato</span></div><div className="rounded-xl border border-[#e2e8df] p-3"><div className="flex items-center justify-between text-xs font-bold"><span>MOT</span><span className="rounded-full bg-[#f1e7dc] px-2 py-1 text-[9px] text-[#795f50]">Originale ARMONIA</span></div><p className="mt-2 text-[9px] font-bold uppercase tracking-wide text-slate-400">Non standardizzato</p></div></div></FeatureCard>
      <FeatureCard className="lg:col-span-4" eyebrow="Economia" title="L’essenziale, ben distinto" copy="Prestazioni, pagamenti, proforma e un riepilogo leggibile."><div className="mt-7 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#345b45] p-3 text-white"><p className="text-[9px] text-white/65">Prestazioni</p><p className="mt-3 text-lg font-bold">12</p></div><div className="rounded-xl bg-[#f2e8de] p-3"><p className="text-[9px] text-[#806c5e]">Stato</p><p className="mt-3 text-xs font-bold text-[#5d5048]">Pagamenti chiari</p></div></div></FeatureCard>
      <FeatureCard className="lg:col-span-4" eyebrow="Modulistica e handout" title="Documenti pronti all’uso" copy="Attestazioni e materiali professionali pronti all’uso."><div className="mt-6 space-y-2">{["Attestazione di presenza","Attestazione di percorso","Handout professionali"].map(x=><div key={x} className="flex items-center gap-2 rounded-lg border border-[#e6ebe3] bg-[#fbfcfa] px-3 py-2 text-[10px] font-bold"><span className="grid h-5 w-5 place-items-center rounded bg-[#e5eee2] text-[#52705a]"><Check/></span>{x}</div>)}</div></FeatureCard>
    </div></section>
    <section className="bg-[#edf3ea]"><div className="mx-auto grid max-w-[1120px] gap-10 px-4 py-20 sm:px-6 md:grid-cols-[1fr_1.15fr] md:items-center lg:px-8"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#66806c]">Pensata dalla pratica</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] sm:text-5xl">Non un gestionale generico adattato alla logopedia.</h2></div><div><p className="text-lg leading-8 text-[#5e7065]">ARMONIA nasce intorno al lavoro reale del logopedista: valutazione, obiettivi terapeutici, sedute, materiali, caregiver e documentazione professionale.</p><div className="mt-6 flex flex-wrap gap-2">{["Profilo linguistico","Fonetico-fonologico","Intelligibilità","CAA","Deglutizione e alimentazione","Follow-up"].map(x=><span key={x} className="rounded-full border border-[#cfddcb] bg-white/70 px-3 py-2 text-xs font-semibold text-[#516a57]">{x}</span>)}</div></div></div></section>
    <section className="bg-[#244a36] text-white"><div className="mx-auto grid max-w-[1120px] gap-10 px-4 py-20 sm:px-6 md:grid-cols-[1.1fr_.9fr] md:items-center lg:px-8"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#bbd0b7]">Affidabilità quotidiana</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-[-.035em] sm:text-5xl">Pensato anche per la parte meno visibile del lavoro.</h2><p className="mt-5 max-w-2xl text-base leading-8 text-white/75">Accessi, dati e continuità operativa restano parte del prodotto, senza diventare rumore nel lavoro clinico.</p></div><ul className="grid gap-3 sm:grid-cols-2 md:grid-cols-1">{["Accesso autenticato","Dati separati per professionista","File professionali protetti","Esportazione dei propri dati"].map(x=><li key={x} className="flex min-h-12 items-center gap-3 rounded-xl border border-white/15 bg-white/[.06] px-4 text-sm font-bold"><span className="text-[#c6dabf]"><Check/></span>{x}</li>)}</ul></div></section>
    <section className="px-4 py-24 sm:px-6"><div className="mx-auto max-w-[920px] rounded-[2rem] border border-[#dbe6d8] bg-white px-6 py-14 text-center shadow-[0_24px_70px_rgba(43,69,55,.08)] sm:px-12"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#66806c]">Il tuo spazio di lavoro</p><h2 className="mt-4 text-3xl font-bold tracking-[-.035em] sm:text-5xl">Porta il lavoro clinico nello stesso spazio.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[#64736b]">Dall’agenda al percorso del paziente, con strumenti e documenti che restano collegati al lavoro reale.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#315d43] px-6 font-bold text-white hover:bg-[#274d37] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500 focus-visible:ring-offset-2">Crea account <Arrow/></Link><Link href="/login" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-[#cedbca] px-6 font-bold text-[#41644b] hover:bg-[#f2f6f0] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Accedi</Link></div></div></section>
    <footer className="border-t border-[#dfe7dc] bg-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-6 px-4 py-10 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><Brand/><nav aria-label="Link nel piè di pagina" className="flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-[#627168]"><Link href="/privacy" className="hover:text-[#31553d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Privacy</Link><Link href="/about" className="hover:text-[#31553d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Chi siamo</Link><Link href="/login" className="hover:text-[#31553d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Accedi</Link><Link href="/signup" className="hover:text-[#31553d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Crea account</Link></nav><p className="text-xs text-[#849088]">© {new Date().getFullYear()} ARMONIA</p></div></footer>
  </main>;
}
