"use client";

import { useMemo, useState } from "react";
import { filterAssets } from "@/lib/asset-bank/catalog";
import { ASSET_PARTS_OF_SPEECH, ASSET_REVIEW_STATUSES, type AssetEntry, type AssetPartOfSpeech, type AssetReviewStatus } from "@/lib/asset-bank/types";

const statusLabels: Record<AssetReviewStatus, string> = { draft: "Draft", reviewed: "Reviewed", approved: "Approved" };
const sourceLabels = { armonia_original: "Originale ARMONIA", public_domain: "Pubblico dominio", creative_commons: "Creative Commons", authorized: "Autorizzato" } as const;
const partLabels: Record<AssetPartOfSpeech, string> = { noun: "Nome", verb: "Verbo", adjective: "Aggettivo", other: "Altro" };

export function AssetBankBrowser({ assets }: { assets: readonly AssetEntry[] }) {
  const [text, setText] = useState(""), [category, setCategory] = useState(""), [partOfSpeech, setPartOfSpeech] = useState<"" | AssetPartOfSpeech>(""), [reviewStatus, setReviewStatus] = useState<"" | AssetReviewStatus>(""), [selected, setSelected] = useState<AssetEntry>();
  const categories = useMemo(() => [...new Set(assets.map((asset) => asset.semanticCategory))].sort((a, b) => a.localeCompare(b, "it")), [assets]);
  const visible = useMemo(() => filterAssets(assets, { text, semanticCategory: category || undefined, partOfSpeech: partOfSpeech || undefined, reviewStatus: reviewStatus || undefined }), [assets, text, category, partOfSpeech, reviewStatus]);
  const counts = Object.fromEntries(ASSET_REVIEW_STATUSES.map((status) => [status, assets.filter((asset) => asset.reviewStatus === status).length])) as Record<AssetReviewStatus, number>;
  return <>
    <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Totale", assets.length], ["Approved", counts.approved], ["Reviewed", counts.reviewed], ["Draft", counts.draft]].map(([label, count]) => <div key={label} className="rounded-2xl border border-violet-100 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{count}</p></div>)}</div>
    <section className="mt-6 rounded-[1.5rem] border border-slate-200 bg-white p-4 sm:p-5" aria-label="Ricerca e filtri Banca Asset">
      <input value={text} onChange={(event) => setText(event.target.value)} placeholder="Cerca lemma, categoria o note…" className="w-full rounded-xl border border-slate-200 px-4 py-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400" />
      <div className="mt-3 grid gap-3 sm:grid-cols-3"><Filter value={category} onChange={setCategory} label="Categoria" options={categories.map((value) => [value, value])} /><Filter value={partOfSpeech} onChange={(value) => setPartOfSpeech(value as typeof partOfSpeech)} label="Parte del discorso" options={ASSET_PARTS_OF_SPEECH.map((value) => [value, partLabels[value]])} /><Filter value={reviewStatus} onChange={(value) => setReviewStatus(value as typeof reviewStatus)} label="Stato" options={ASSET_REVIEW_STATUSES.map((value) => [value, statusLabels[value]])} /></div>
    </section>
    {!assets.length ? <section className="mt-6 rounded-[1.75rem] border border-dashed border-violet-200 bg-violet-50/40 px-5 py-12 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-violet-100 text-2xl" aria-hidden="true">◇</div><h2 className="mt-5 text-xl font-bold">La Banca Asset è pronta</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-600">Non sono ancora presenti asset approvati. Le immagini compariranno qui dopo il workflow editoriale e la validazione del catalogo.</p></section> : visible.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((asset) => <button key={asset.id} type="button" onClick={() => setSelected(asset)} className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white text-left transition hover:-translate-y-0.5 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400"><div className="grid aspect-[4/3] place-items-center bg-slate-50 p-4"><img src={asset.imagePath} alt={asset.altText} className="h-full w-full object-contain" /></div><div className="p-4"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-bold">{asset.label}</h2><StatusBadge status={asset.reviewStatus} /></div><p className="mt-2 text-sm text-slate-500">{asset.semanticCategory}{asset.partOfSpeech ? ` · ${partLabels[asset.partOfSpeech]}` : ""}</p><p className="mt-3 text-xs font-bold text-slate-500">{sourceLabels[asset.sourceType]}</p></div></button>)}</div> : <p className="mt-6 rounded-2xl border border-dashed border-slate-200 bg-white p-8 text-center text-sm text-slate-500">Nessun asset corrisponde ai filtri selezionati.</p>}
    {selected && <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/35 p-0 sm:place-items-center sm:p-6" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setSelected(undefined); }}><section role="dialog" aria-modal="true" aria-labelledby="asset-detail-title" className="max-h-[90dvh] w-full overflow-y-auto rounded-t-[2rem] bg-white p-5 shadow-2xl sm:max-w-2xl sm:rounded-[2rem] sm:p-7"><div className="flex items-start justify-between gap-4"><div><StatusBadge status={selected.reviewStatus} /><h2 id="asset-detail-title" className="mt-3 text-2xl font-bold">{selected.label}</h2></div><button type="button" onClick={() => setSelected(undefined)} aria-label="Chiudi dettaglio asset" className="grid h-11 w-11 place-items-center rounded-full bg-slate-100 text-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400">×</button></div><img src={selected.imagePath} alt={selected.altText} className="mt-5 max-h-64 w-full rounded-2xl bg-slate-50 object-contain p-4" /><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Detail label="ID" value={selected.id} /><Detail label="Categoria" value={selected.semanticCategory} /><Detail label="Sottocategoria" value={selected.semanticSubcategory} /><Detail label="Parte del discorso" value={selected.partOfSpeech ? partLabels[selected.partOfSpeech] : undefined} /><Detail label="Struttura sillabica" value={selected.syllableStructure} /><Detail label="Fascia d’età" value={selected.ageBand} /><Detail label="Pubblico" value={selected.intendedAudience} /><Detail label="Origine" value={sourceLabels[selected.sourceType]} /><Detail label="Autore" value={selected.author} /><Detail label="Fonte" value={selected.sourceName} /><Detail label="Licenza/base d’uso" value={selected.licenseName} /><Detail label="Attribuzione" value={selected.attributionText} /><Detail label="Uso commerciale dichiarato" value={selected.commercialUseAllowed ? "Sì" : "No"} /></dl><PhonologyDetails asset={selected} />{selected.notes && <div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Note</p><p className="mt-2 text-sm leading-6">{selected.notes}</p></div>}</section></div>}
  </>;
}

function Filter({ value, onChange, label, options }: { value: string; onChange: (value: string) => void; label: string; options: readonly (readonly [string, string])[] }) { return <label className="text-xs font-bold text-slate-500">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400"><option value="">Tutti</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function StatusBadge({ status }: { status: AssetReviewStatus }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${status === "approved" ? "bg-sage-100 text-sage-800" : status === "reviewed" ? "bg-sky-100 text-sky-800" : "bg-amber-100 text-amber-800"}`}>{statusLabels[status]}</span>; }
function Detail({ label, value }: { label: string; value?: string }) { if (!value) return null; return <div><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 break-words text-sm text-slate-700">{value}</dd></div>; }
function PhonologyDetails({ asset }: { asset: AssetEntry }) {
  const hasData = Boolean(asset.syllabification || asset.syllableCount || asset.phonemicTranscription || asset.phonemes?.length || asset.consonantClusters?.length || asset.geminates?.length || asset.pronunciationNotes || asset.phonologyReviewStatus);
  const position = { initial: "iniziale", medial: "mediale", final: "finale" } as const;
  return <section className="mt-6 border-t border-slate-200 pt-5" aria-labelledby="linguistic-data-title"><h3 id="linguistic-data-title" className="font-bold">Dati linguistici</h3>{!hasData ? <p className="mt-2 text-sm text-slate-500">Non ancora revisionato.</p> : <dl className="mt-4 grid gap-4 sm:grid-cols-2"><Detail label="Sillabazione" value={asset.syllabification} /><Detail label="Numero sillabe" value={asset.syllableCount?.toString()} /><Detail label="Trascrizione fonemica" value={asset.phonemicTranscription} /><Detail label="Fonemi" value={asset.phonemes?.map((item) => `/${item.symbol}/ · ${position[item.position]}${item.syllable ? ` · sillaba ${item.syllable}` : ""}`).join(", ")} /><Detail label="Cluster consonantici" value={asset.consonantClusters?.map((item) => `/${item.phonemes.join("")}/ · ${position[item.position]}${item.syllable ? ` · sillaba ${item.syllable}` : ""}`).join(", ")} /><Detail label="Geminate" value={asset.geminates?.map((symbol) => `/${symbol}/`).join(", ")} /><Detail label="Stato revisione" value={asset.phonologyReviewStatus === "reviewed" ? "Revisionato" : asset.phonologyReviewStatus === "needs_review" ? "Da verificare" : "Non revisionato"} /><Detail label="Note di pronuncia" value={asset.pronunciationNotes} /></dl>}</section>;
}
