"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";import type {User} from "@supabase/supabase-js";import type {AppData,Appointment,Goal,Material,Patient,Profile,Session} from "@/lib/types";import {today,uid} from "@/lib/types";import {createClient} from "@/lib/supabase/client";import {appointmentRow,goalRow,loadCloudData,materialRow,patientRow,profileRow,replaceLinks,sessionRow,signedFileBlob} from "@/lib/supabase/repository";
const KEY="armonia-demo-v2",now=()=>new Date().toISOString();
const emptyData:AppData={patients:[],appointments:[],sessions:[],goals:[],materials:[],profile:{firstName:"",lastName:"",profession:"",email:"",studio:""}};
const seed=():AppData=>{const ids=[uid(),uid(),uid(),uid(),uid()];const names=[["Livia","Gelsi","2019-03-11"],["Tomaso","Verdi","2017-07-20"],["Nora","Lenti","2021-01-14"],["Elia","Costa","2018-05-02"],["Milo","Farri","2020-10-09"]];const patients=names.map((n,i):Patient=>({id:ids[i],firstName:n[0],lastName:n[1],birthDate:n[2],contact:"",guardian:i<3?"Genitore demo":"",school:"Scuola demo",schoolClass:"",referralReason:["Articolazione del suono /r/","Comprensione del testo","Espansione lessicale","Fluenza e ritmo","Consapevolezza fonologica"][i],notes:"Dati dimostrativi inventati.",status:"active",createdAt:now()}));return {patients,appointments:[{id:uid(),patientId:ids[0],date:today(),time:"09:30",duration:45,type:"regular",notes:"Portare le carte del memory.",createdAt:now()},{id:uid(),patientId:ids[1],date:today(),time:"11:00",duration:45,type:"regular",notes:"",createdAt:now()},{id:uid(),patientId:ids[2],date:today(),time:"15:30",duration:45,type:"checkup",notes:"Chiedere feedback alla mamma.",createdAt:now()}],sessions:[{id:uid(),patientId:ids[0],date:today(),duration:45,goalIds:[],activities:"Coppie minime e produzione guidata.",response:"Buona",helpLevel:"Minimo",result:"Ha lavorato bene con le coppie minime.",nextPlan:"Riprendere con esercizi di produzione in frase.",homework:"",notes:"",materialIds:[],createdAt:now()}],goals:patients.map(p=>({id:uid(),patientId:p.id,title:p.referralReason,description:"",priority:2,status:"in_progress",progress:45,createdAt:now()})),materials:[],profile:{firstName:"Anna",lastName:"Bianchi",profession:"Logopedista",email:"anna@esempio.it",studio:"Studio Armonia"}}};
type Connection={kind:"local"|"cloud"|"error";label:string;message:string};type Store={data:AppData;ready:boolean;authReady:boolean;user:User|null;connection:Connection;signIn:(email:string,password:string)=>Promise<string|null>;signOut:()=>Promise<void>;savePatient:(p:Patient)=>Promise<void>;deletePatient:(id:string)=>Promise<void>;saveAppointment:(a:Appointment)=>Promise<void>;deleteAppointment:(id:string)=>Promise<void>;saveSession:(s:Session)=>Promise<void>;deleteSession:(id:string)=>Promise<void>;saveGoal:(g:Goal)=>Promise<void>;deleteGoal:(id:string)=>Promise<void>;saveMaterial:(m:Material,file?:File)=>Promise<void>;deleteMaterial:(id:string)=>Promise<void>;openMaterial:(m:Material)=>Promise<void>;getMaterialFile:(id:string)=>Promise<Blob|undefined>;saveProfile:(p:Profile)=>Promise<void>;reload:()=>Promise<void>};
const C=createContext<Store|null>(null);const hasCloud=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)&&process.env.NEXT_PUBLIC_DATA_MODE!=="local";
const localDb=()=>new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open("armonia-files",1);r.onupgradeneeded=()=>r.result.createObjectStore("files");r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
async function putLocal(id:string,file:File){const d=await localDb();await new Promise<void>((ok,no)=>{const t=d.transaction("files","readwrite");t.objectStore("files").put(file,id);t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}async function getLocal(id:string){const d=await localDb();return new Promise<Blob|undefined>((ok,no)=>{const r=d.transaction("files").objectStore("files").get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function removeLocal(id:string){const d=await localDb();await new Promise<void>((ok,no)=>{const t=d.transaction("files","readwrite");t.objectStore("files").delete(id);t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
export function DataProvider({children}:{children:React.ReactNode}){const client=useMemo(()=>hasCloud?createClient():null,[]);const [data,setData]=useState<AppData>(emptyData),[ready,setReady]=useState(false),[authReady,setAuthReady]=useState(false),[user,setUser]=useState<User|null>(null),[error,setError]=useState<string|null>(null);const up=<T extends{id:string}>(list:T[],item:T)=>list.some(x=>x.id===item.id)?list.map(x=>x.id===item.id?item:x):[item,...list];const fail=(e:unknown)=>{console.error(e);const message=e instanceof Error?e.message:typeof e==="object"&&e!==null&&"message" in e?String(e.message):"Errore di connessione a Supabase";setError(message)};
 const reload=async()=>{if(!client||!user)return;try{setData(await loadCloudData(client,user));setError(null);setReady(true)}catch(e){fail(e);setReady(true)}};
 useEffect(()=>{if(!client){try{const raw=localStorage.getItem(KEY);setData(raw?JSON.parse(raw):seed())}finally{setReady(true);setAuthReady(true)}return}let active=true;client.auth.getSession().then(async({data:s,error:e})=>{if(!active)return;if(e){fail(e);setAuthReady(true);return}setUser(s.session?.user||null);setAuthReady(true);if(s.session?.user){try{setData(await loadCloudData(client,s.session.user));setReady(true)}catch(err){fail(err);setReady(true)}}else setReady(true)});const {data:sub}=client.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);if(session?.user){queueMicrotask(async()=>{try{setData(await loadCloudData(client,session.user));setError(null);setReady(true)}catch(err){fail(err)}})}else{setData(emptyData);setReady(true)}});return()=>{active=false;sub.subscription.unsubscribe()}},[client]);
 useEffect(()=>{if(!client&&ready)localStorage.setItem(KEY,JSON.stringify(data))},[client,data,ready]);
 const signIn=async(email:string,password:string)=>{if(!client)return"Supabase non è attivo";const {error:e}=await client.auth.signInWithPassword({email,password});if(e)return e.message;return null};const signOut=async()=>{if(client)await client.auth.signOut()};
 const savePatient=async(p:Patient)=>{setData(d=>({...d,patients:up(d.patients,p)}));if(client&&user)try{const {error:e}=await client.from("patients").upsert(patientRow(p,user.id));if(e)throw e;setError(null)}catch(e){fail(e);throw e}};
 const deletePatient=async(id:string)=>{setData(d=>({...d,patients:d.patients.filter(x=>x.id!==id),appointments:d.appointments.filter(x=>x.patientId!==id),sessions:d.sessions.filter(x=>x.patientId!==id),goals:d.goals.filter(x=>x.patientId!==id),materials:d.materials.map(m=>({...m,patientIds:m.patientIds.filter(x=>x!==id)}))}));if(client)try{const {error:e}=await client.from("patients").delete().eq("id",id);if(e)throw e}catch(e){fail(e)}};
 const saveAppointment=async(a:Appointment)=>{setData(d=>({...d,appointments:up(d.appointments,a)}));if(client&&user)try{const {error:e}=await client.from("appointments").upsert(appointmentRow(a,user.id));if(e)throw e;setError(null)}catch(e){fail(e);throw e}};
 const deleteAppointment=async(id:string)=>{setData(d=>({...d,appointments:d.appointments.filter(x=>x.id!==id)}));if(client)try{const {error:e}=await client.from("appointments").delete().eq("id",id);if(e)throw e}catch(e){fail(e)}};
 const saveSession=async(s:Session)=>{setData(d=>({...d,sessions:up(d.sessions,s)}));if(client&&user)try{let r=await client.from("sessions").upsert(sessionRow(s,user.id));if(r.error)throw r.error;await replaceLinks(client,"session_materials","session_id",s.id,"material_id",s.materialIds);const old=await client.from("session_goals").delete().eq("session_id",s.id);if(old.error)throw old.error;if(s.goalIds.length){const links=await client.from("session_goals").insert(s.goalIds.map(goal_id=>({session_id:s.id,goal_id})));if(links.error)throw links.error}setError(null)}catch(e){fail(e);throw e}};
 const deleteSession=async(id:string)=>{setData(d=>({...d,sessions:d.sessions.filter(x=>x.id!==id)}));if(client)try{const {error:e}=await client.from("sessions").delete().eq("id",id);if(e)throw e}catch(e){fail(e)}};
 const saveGoal=async(g:Goal)=>{setData(d=>({...d,goals:up(d.goals,g)}));if(client&&user)try{const {error:e}=await client.from("goals").upsert(goalRow(g,user.id));if(e)throw e;setError(null)}catch(e){fail(e);throw e}};
 const deleteGoal=async(id:string)=>{setData(d=>({...d,goals:d.goals.filter(x=>x.id!==id),sessions:d.sessions.map(s=>({...s,goalIds:s.goalIds.filter(x=>x!==id)}))}));if(client)try{const {error:e}=await client.from("goals").delete().eq("id",id);if(e)throw e}catch(e){fail(e)}};
 const saveMaterial=async(m:Material,file?:File)=>{try{let next=m;if(client&&user&&file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${user.id}/${m.id}/${safe}`;const upload=await client.storage.from("therapy-materials").upload(path,file,{upsert:true,contentType:file.type});if(upload.error)throw upload.error;if(m.storagePath&&m.storagePath!==path)await client.storage.from("therapy-materials").remove([m.storagePath]);next={...m,storagePath:path,fileName:file.name,mimeType:file.type,size:file.size}}else if(!client&&file){await putLocal(m.id,file);next={...m,fileName:file.name,mimeType:file.type,size:file.size}}setData(d=>({...d,materials:up(d.materials,next)}));if(client&&user){const row=await client.from("materials").upsert(materialRow(next,user.id));if(row.error)throw row.error;await replaceLinks(client,"patient_materials","material_id",next.id,"patient_id",next.patientIds)}setError(null)}catch(e){fail(e);throw e}};
 const deleteMaterial=async(id:string)=>{const m=data.materials.find(x=>x.id===id);if(client){try{if(m?.storagePath){const r=await client.storage.from("therapy-materials").remove([m.storagePath]);if(r.error)throw r.error}const r=await client.from("materials").delete().eq("id",id);if(r.error)throw r.error}catch(e){fail(e);return}}else await removeLocal(id);setData(d=>({...d,materials:d.materials.filter(x=>x.id!==id)}))};
 const getMaterialFile=async(id:string)=>{const m=data.materials.find(x=>x.id===id);if(!m)return;if(client){if(!m.storagePath)return;try{return await signedFileBlob(client,m.storagePath)}catch(e){fail(e);return}}return getLocal(id)};const openMaterial=async(m:Material)=>{if(m.externalUrl){window.open(m.externalUrl,"_blank","noopener");return}const b=await getMaterialFile(m.id);if(!b)return;const url=URL.createObjectURL(b);window.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)};
 const saveProfile=async(profile:Profile)=>{setData(d=>({...d,profile}));if(client&&user)try{const r=await client.from("profiles").upsert(profileRow(profile,user.id));if(r.error)throw r.error;setError(null)}catch(e){fail(e);throw e}};
 const connection:Connection=!client?{kind:"local",label:"Locale",message:"Modalità demo · dati salvati solo su questo dispositivo"}:error?{kind:"error",label:"Errore di connessione",message:error}:{kind:"cloud",label:"Cloud connesso",message:"Modalità cloud · dati sincronizzati tra i dispositivi"};return <C.Provider value={{data,ready,authReady,user,connection,signIn,signOut,savePatient,deletePatient,saveAppointment,deleteAppointment,saveSession,deleteSession,saveGoal,deleteGoal,saveMaterial,deleteMaterial,openMaterial,getMaterialFile,saveProfile,reload}}>{children}</C.Provider>}
export const useData=()=>{const x=useContext(C);if(!x)throw new Error("DataProvider missing");return x};export const isCloudConfigured=hasCloud;
