"use client";

import { useState } from "react";
import { editExerciseDraft, exerciseDraftItemKey, moveExerciseDraftItem, removeExerciseDraftItem, resetExerciseDraft, type ExerciseDraft } from "@/lib/exercise-lab/exercise-draft";

export function ExerciseDraftEditor({ draft, initialDraft, onChange }: { draft: ExerciseDraft; initialDraft: ExerciseDraft; onChange: (draft: ExerciseDraft) => void }) {
  const [shownAnswers, setShownAnswers] = useState<Set<string>>(new Set());
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Titolo<input className="field" value={draft.title} onChange={(event) => onChange(editExerciseDraft(draft, { title: event.target.value }))} /></label><label className="text-xs font-bold text-slate-500">Istruzione<input className="field" value={draft.instructions} onChange={(event) => onChange(editExerciseDraft(draft, { instructions: event.target.value }))} /></label></div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-y border-slate-100 py-4"><p className="text-sm text-slate-500"><strong className="text-slate-800">{draft.items.length}</strong> {draft.items.length === 1 ? "elemento" : "elementi"}</p><button type="button" onClick={() => { setShownAnswers(new Set()); onChange(resetExerciseDraft(initialDraft)); }} className="btn btn-quiet">Ripristina</button></div>
    {!draft.items.length ? <p className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">L’esercizio non contiene più elementi. Usa Ripristina per recuperare la selezione iniziale.</p> : <div className="space-y-4">{draft.items.map((_, index) => <article key={exerciseDraftItemKey(draft, index)} className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><DraftItem draft={draft} index={index} shownAnswers={shownAnswers} onToggleAnswer={(id) => setShownAnswers((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; })} /><div className="mt-4 flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-3"><button type="button" disabled={index === 0} onClick={() => onChange(moveExerciseDraftItem(draft, index, -1))} className="min-h-11 rounded-xl px-3 text-sm font-semibold text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-35">Sposta su</button><button type="button" disabled={index === draft.items.length - 1} onClick={() => onChange(moveExerciseDraftItem(draft, index, 1))} className="min-h-11 rounded-xl px-3 text-sm font-semibold text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-35">Sposta giù</button><button type="button" onClick={() => onChange(removeExerciseDraftItem(draft, index))} className="min-h-11 rounded-xl px-3 text-sm font-semibold text-rose-700 hover:bg-rose-50">Rimuovi</button></div></article>)}</div>}
  </div>;
}

function DraftItem({ draft, index, shownAnswers, onToggleAnswer }: { draft: ExerciseDraft; index: number; shownAnswers: Set<string>; onToggleAnswer: (id: string) => void }) {
  if (draft.kind === "picture_naming") { const item = draft.items[index]; return <div className="mx-auto max-w-sm"><img src={item.imagePath} alt={item.altText} className="aspect-[4/3] w-full rounded-xl bg-slate-50 object-contain" /><p className="mt-2 text-center text-sm font-semibold text-slate-500">{item.text}</p></div>; }
  if (draft.kind === "minimal_pairs") { const item = draft.items[index]; return <div><div className="grid grid-cols-2 gap-3">{[[item.imagePathA, item.wordA], [item.imagePathB, item.wordB]].map(([path, word]) => <div key={word} className="rounded-xl bg-slate-50 p-3 text-center">{path && <img src={path} alt="" className="mx-auto aspect-square max-h-40 w-full object-contain" />}<p className="mt-2 text-lg font-bold text-slate-800">{word}</p></div>)}</div></div>; }
  if (draft.kind === "repetition") { const item = draft.items[index]; return <div className="text-center"><p className="text-2xl font-bold text-slate-900">{item.text}</p><p className="mt-2 text-sm text-slate-500">{item.syllabification}</p></div>; }
  if (draft.kind === "sentence_reading") { const item = draft.items[index]; return <div className="flex gap-3"><span className="font-bold text-violet-600">{index + 1}.</span><div><p className="text-base font-semibold leading-7 text-slate-800">{item.text}</p><p className="mt-1 text-xs text-slate-400">{item.wordCount} parole</p></div></div>; }
  const item = draft.items[index];
  return <div><h3 className="text-xl font-bold text-slate-900">{item.passageTitle}</h3><p className="mt-4 whitespace-pre-line leading-8 text-slate-700">{item.text}</p><section className="mt-6 border-t border-slate-100 pt-5"><h4 className="font-bold text-slate-900">Domande</h4><ol className="mt-3 space-y-4">{item.questions.map((question) => <li key={question.id} className="ml-5 list-decimal pl-1"><p className="font-semibold leading-6 text-slate-800">{question.prompt}</p>{question.expectedAnswer && <div className="mt-2"><button type="button" aria-expanded={shownAnswers.has(question.id)} onClick={() => onToggleAnswer(question.id)} className="text-sm font-semibold text-violet-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400">{shownAnswers.has(question.id) ? "Nascondi risposta suggerita" : "Mostra risposta suggerita"}</button>{shownAnswers.has(question.id) && <p className="mt-2 rounded-xl bg-violet-50 px-3 py-2 text-sm text-violet-950">{question.expectedAnswer}</p>}</div>}</li>)}</ol></section></div>;
}
