"use client";

import { useMemo, useState } from "react";
import { useData } from "@/components/data-provider";
import { ExerciseDraftEditor } from "@/components/exercise-draft-editor";
import { WorksheetDraftEditor } from "@/components/worksheet-draft-editor";
import { WorksheetPreview } from "@/components/worksheet-preview";
import { WorksheetPrintView } from "@/components/worksheet-print-view";
import {
  buildImageNamingPreview, buildReadingComprehensionPreview, buildRepetitionPreview, buildSentenceReadingPreview,
  exerciseBricks, getAvailableClusterPhonemes, getAvailableGeminates, getAvailableReadingAudiences,
  getAvailableSentenceAudiences, getAvailableWordPhonemes,
} from "@/lib/exercise-lab/bricks";
import { createExerciseDraft, resetExerciseDraft, type ExerciseDraft } from "@/lib/exercise-lab/exercise-draft";
import {
  getImageNamingCandidates, getMinimalPairCandidates, getMinimalPairContrastOptions, getRepetitionCandidates,
  getSentenceReadingCandidates, minimalPairContrastKey, minimalPairContrastLabel, searchCandidates,
  selectedInOrder, toggleSelectedId,
} from "@/lib/exercise-lab/manual-selection";
import { addWorksheetBlock, createWorksheetDraft, updateWorksheetBlock, type ExerciseBlockDraft } from "@/lib/exercise-lab/worksheet-draft";
import type { ContentAudience, PassageQuestionType } from "@/lib/content-bank/types";
import type { ExerciseBrickCode, ExercisePreview, ImageNamingItem, MinimalPairItem, ReadingComprehensionPreview, RepetitionItem, SentenceReadingItem, SyllableCountFilter } from "@/lib/exercise-lab/types";
import { missingRecipeContentIds, type ExerciseRecipeConfiguration, type ExerciseRecipeV1 } from "@/lib/exercise-lab/recipes";
import { uid } from "@/lib/types";

const positions = [{ value: "", label: "Qualsiasi" }, { value: "initial", label: "Iniziale" }, { value: "medial", label: "Mediale" }, { value: "final", label: "Finale" }] as const;
const counts = [4, 6, 8, 10, 12];
type SelectionMode = "manual" | "automatic";
type WorkspaceView = "compose" | "choose" | "add" | "edit" | "preview" | "print";
type Candidate = ImageNamingItem | MinimalPairItem | RepetitionItem | SentenceReadingItem;

export function ExerciseLabBuilder() {
  const { data, saveExerciseRecipe, deleteExerciseRecipe } = useData();
  const [worksheet, setWorksheet] = useState(createWorksheetDraft);
  const [view, setView] = useState<WorkspaceView>("compose");
  const [editingBlock, setEditingBlock] = useState<ExerciseBlockDraft>();
  const [editingExercise, setEditingExercise] = useState<ExerciseDraft>();
  const [brick, setBrick] = useState<ExerciseBrickCode>("image_naming"), [mode, setMode] = useState<SelectionMode>("manual"), [itemCount, setItemCount] = useState(6);
  const includeDrafts = false;
  const [phoneme, setPhoneme] = useState(""), [position, setPosition] = useState(""), [syllables, setSyllables] = useState<"" | `${number}` | "4+">("");
  const [cluster, setCluster] = useState(""), [geminate, setGeminate] = useState(""), [requireImages, setRequireImages] = useState(false), [kind, setKind] = useState<"word" | "nonword" | "both">("both");
  const [showWords, setShowWords] = useState(true), [showIpa, setShowIpa] = useState(false), [query, setQuery] = useState(""), [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [contrastKey, setContrastKey] = useState(""), [readingAudience, setReadingAudience] = useState(""), [passageId, setPassageId] = useState(""), [shownAnswers, setShownAnswers] = useState<Set<string>>(new Set());
  const [sentenceAudience, setSentenceAudience] = useState(""), [sentenceCount, setSentenceCount] = useState(5);
  const [recipeDialogOpen, setRecipeDialogOpen] = useState(false), [recipeName, setRecipeName] = useState(""), [recipeDescription, setRecipeDescription] = useState(""), [recipeNotice, setRecipeNotice] = useState("");
  const wordPhonemes = getAvailableWordPhonemes(includeDrafts), clusters = getAvailableClusterPhonemes(includeDrafts), geminates = getAvailableGeminates(includeDrafts);
  const readingAudiences = getAvailableReadingAudiences(includeDrafts), sentenceAudiences = getAvailableSentenceAudiences(includeDrafts);
  const parsedSyllables = syllables ? (syllables === "4+" ? "4+" : Number(syllables)) as SyllableCountFilter : undefined;
  const commonPhonology = { includeDrafts, phoneme: phoneme || undefined, position: position as never || undefined, syllableCount: parsedSyllables, clusterPhoneme: cluster || undefined, geminate: geminate || undefined };

  const imageCandidates = useMemo(() => getImageNamingCandidates(commonPhonology), [cluster, geminate, includeDrafts, parsedSyllables, phoneme, position]);
  const pairBaseCandidates = useMemo(() => getMinimalPairCandidates({ includeDrafts, position: position as never || undefined, requireImages }), [includeDrafts, position, requireImages]);
  const contrastOptions = useMemo(() => getMinimalPairContrastOptions(pairBaseCandidates), [pairBaseCandidates]);
  const pairCandidates = useMemo(() => contrastKey ? pairBaseCandidates.filter((item) => minimalPairContrastKey(item) === contrastKey) : pairBaseCandidates, [contrastKey, pairBaseCandidates]);
  const repetitionCandidates = useMemo(() => getRepetitionCandidates({ ...commonPhonology, contentKind: kind }), [cluster, geminate, includeDrafts, kind, parsedSyllables, phoneme, position]);
  const sentenceCandidates = useMemo(() => getSentenceReadingCandidates({ includeDrafts, audience: sentenceAudience as ContentAudience || undefined }), [includeDrafts, sentenceAudience]);
  const allImageCandidates = useMemo(() => getImageNamingCandidates({ includeDrafts }), [includeDrafts]);
  const allPairCandidates = useMemo(() => getMinimalPairCandidates({ includeDrafts }), [includeDrafts]);
  const allRepetitionCandidates = useMemo(() => getRepetitionCandidates({ includeDrafts, contentKind: kind }), [includeDrafts, kind]);
  const allSentenceCandidates = useMemo(() => getSentenceReadingCandidates({ includeDrafts }), [includeDrafts]);
  const readingPreview = useMemo(() => buildReadingComprehensionPreview({ includeDrafts, audience: readingAudience as ContentAudience || undefined, passageId: passageId || undefined }), [includeDrafts, passageId, readingAudience]);

  const candidates: Candidate[] = brick === "image_naming" ? imageCandidates : brick === "minimal_pairs" ? pairCandidates : brick === "word_nonword_repetition" ? repetitionCandidates : brick === "sentence_reading" ? sentenceCandidates : [];
  const allCandidates: Candidate[] = brick === "image_naming" ? allImageCandidates : brick === "minimal_pairs" ? allPairCandidates : brick === "word_nonword_repetition" ? allRepetitionCandidates : brick === "sentence_reading" ? allSentenceCandidates : [];
  const visibleCandidates = searchCandidates(candidates, query, candidateLabel);
  const selectedItems = selectedInOrder(selectedIds, allCandidates, candidateId);
  const automaticPreview = useMemo(() => {
    if (brick === "image_naming") return buildImageNamingPreview({ ...commonPhonology, itemCount });
    if (brick === "minimal_pairs") return asPreview("minimal_pairs", "Coppie minime", pairCandidates.slice(0, itemCount), itemCount, pairCandidates.length);
    if (brick === "word_nonword_repetition") return buildRepetitionPreview({ ...commonPhonology, itemCount, contentKind: kind });
    if (brick === "sentence_reading") return buildSentenceReadingPreview({ includeDrafts, itemCount: sentenceCount, audience: sentenceAudience as ContentAudience || undefined });
    return readingPreview;
  }, [brick, cluster, geminate, includeDrafts, itemCount, kind, pairCandidates, parsedSyllables, phoneme, position, readingPreview, sentenceAudience, sentenceCount]);
  const preparedPreview = brick === "reading_comprehension" ? readingPreview : mode === "automatic" ? automaticPreview : asPreview(brick, exerciseBricks.find((entry) => entry.code === brick)?.title || "Attività", selectedItems, selectedItems.length, selectedItems.length);
  const preparedExercise = createExerciseDraft(preparedPreview as Parameters<typeof createExerciseDraft>[0]);

  function chooseBrick(next: ExerciseBrickCode) { setBrick(next); setQuery(""); setSelectedIds([]); setPhoneme(""); setContrastKey(""); setPosition(""); setPassageId(""); setShownAnswers(new Set()); setView("add"); }
  function addCurrentActivity() { if (!preparedExercise) return; setWorksheet((current) => addWorksheetBlock(current, preparedExercise)); setSelectedIds([]); setView("compose"); }
  function openEditor(block: ExerciseBlockDraft) { setEditingBlock(block); setEditingExercise(resetExerciseDraft(block.exercise)); setView("edit"); }
  function saveEditedActivity() { if (!editingBlock || !editingExercise) return; setWorksheet((current) => updateWorksheetBlock(current, editingBlock.id, editingExercise)); setEditingBlock(undefined); setEditingExercise(undefined); setView("compose"); }
  async function saveCurrentRecipe() {
    const configuration = currentRecipeConfiguration();
    if (!recipeName.trim() || !configuration) { setRecipeNotice("Completa la configurazione e assegna un nome alla ricetta."); return; }
    const timestamp = new Date().toISOString();
    await saveExerciseRecipe({ id: uid(), schemaVersion: 1, kind: brick, name: recipeName.trim(), description: recipeDescription.trim() || undefined, configuration, createdAt: timestamp, updatedAt: timestamp });
    setRecipeDialogOpen(false); setRecipeName(""); setRecipeDescription(""); setRecipeNotice("Ricetta salvata.");
  }
  function currentRecipeConfiguration(): ExerciseRecipeConfiguration | undefined {
    if (brick === "reading_comprehension") return passageId ? { kind: brick, selectedPassageId: passageId } : undefined;
    if (mode === "manual") return selectedIds.length ? { kind: brick, mode, ...(brick === "word_nonword_repetition" ? { contentKind: kind } : {}), selectedContentIds: [...selectedIds] } as ExerciseRecipeConfiguration : undefined;
    if (brick === "minimal_pairs") return { kind: brick, mode, contrastKey: contrastKey || undefined, position: position as "initial" | "medial" | "final" || undefined, requireImages, itemCount };
    if (brick === "sentence_reading") return { kind: brick, mode, audience: sentenceAudience as ContentAudience || undefined, itemCount: sentenceCount };
    return { kind: brick, mode, ...(brick === "word_nonword_repetition" ? { contentKind: kind } : {}), phoneme: phoneme || undefined, position: position as "initial" | "medial" | "final" || undefined, syllableCount: parsedSyllables, clusterPhoneme: cluster || undefined, geminate: geminate || undefined, itemCount } as ExerciseRecipeConfiguration;
  }
  function useRecipe(recipe: ExerciseRecipeV1) {
    const config = recipe.configuration; setBrick(recipe.kind); setQuery(""); setRecipeNotice("");
    if (config.kind === "reading_comprehension") { setReadingAudience(""); setPassageId(config.selectedPassageId); const missing = missingRecipeContentIds(recipe, buildReadingComprehensionPreview({ includeDrafts }).availablePassages.map((item) => item.passageId)); if (missing.length) setRecipeNotice("Il brano salvato non è più disponibile. Scegline uno nuovo."); }
    else {
      setMode(config.mode);
      if (config.mode === "manual") {
        const source = config.kind === "image_naming" ? getImageNamingCandidates({ includeDrafts }) : config.kind === "minimal_pairs" ? getMinimalPairCandidates({ includeDrafts }) : config.kind === "word_nonword_repetition" ? getRepetitionCandidates({ includeDrafts, contentKind: config.contentKind }) : getSentenceReadingCandidates({ includeDrafts });
        const available = source.map(candidateId), missing = missingRecipeContentIds(recipe, available); setSelectedIds(config.selectedContentIds.filter((id) => available.includes(id)));
        if (missing.length) setRecipeNotice(`${missing.length} contenuti salvati non sono più disponibili. La ricetta non li ha sostituiti.`);
      } else {
        setSelectedIds([]); setItemCount(config.itemCount);
        if (config.kind === "minimal_pairs") { setContrastKey(config.contrastKey || ""); setPosition(config.position || ""); setRequireImages(config.requireImages); }
        if (config.kind === "sentence_reading") { setSentenceAudience(config.audience || ""); setSentenceCount(config.itemCount); }
        if (config.kind === "image_naming" || config.kind === "word_nonword_repetition") { setPhoneme(config.phoneme || ""); setPosition(config.position || ""); setSyllables(config.syllableCount ? String(config.syllableCount) as typeof syllables : ""); setCluster(config.clusterPhoneme || ""); setGeminate(config.geminate || ""); if (config.kind === "word_nonword_repetition") setKind(config.contentKind); }
      }
    }
    setView("add");
  }

  if (view === "print") return <WorksheetPrintView worksheet={worksheet} onBack={() => setView("preview")} />;
  if (view === "preview") return <div className="mt-8"><WorksheetPreview worksheet={worksheet} onBack={() => setView("compose")} onPrint={() => setView("print")} /></div>;
  if (view === "edit" && editingBlock && editingExercise) return <FocusedWorkspace title="Modifica attività" onBack={() => setView("compose")}><ExerciseDraftEditor draft={editingExercise} initialDraft={editingBlock.initialExercise} onChange={setEditingExercise} /><div className="sticky bottom-0 mt-8 flex justify-end border-t border-slate-100 bg-white/95 py-4 backdrop-blur"><button type="button" onClick={saveEditedActivity} className="btn btn-primary">Salva modifiche</button></div></FocusedWorkspace>;
  if (view === "choose") return <FocusedWorkspace title="Che attività vuoi aggiungere?" onBack={() => setView("compose")}><RecipeList recipes={data.exerciseRecipes} onUse={useRecipe} onDelete={deleteExerciseRecipe} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{exerciseBricks.map((entry) => <button type="button" key={entry.code} onClick={() => chooseBrick(entry.code)} className="group min-h-36 rounded-3xl border border-slate-200 bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500"><strong className="block text-base text-slate-900">{entry.title}</strong><span className="mt-3 block text-sm leading-6 text-slate-500">{activityDescription(entry.code)}</span><span className="mt-4 block text-sm font-bold text-emerald-800">Scegli →</span></button>)}</div></FocusedWorkspace>;
  if (view === "compose") return <div className="mt-8"><WorksheetDraftEditor worksheet={worksheet} onChange={setWorksheet} onAddActivity={() => setView("choose")} onEditActivity={openEditor} onPreview={() => setView("preview")} /></div>;

  return <FocusedWorkspace title={exerciseBricks.find((entry) => entry.code === brick)?.title || "Nuova attività"} onBack={() => setView("choose")}>
    <div className="space-y-6">
      <Step title="Scegli i contenuti">
        {brick !== "reading_comprehension" && <ModeSwitch value={mode} onChange={(next) => { setMode(next); setSelectedIds([]); }} />}
        <div className="mt-5">{brick === "reading_comprehension" ? <ReadingConfiguration preview={readingPreview} audiences={readingAudiences} audience={readingAudience} passageId={passageId} onAudienceChange={(value) => { setReadingAudience(value); setPassageId(""); }} onPassageChange={setPassageId} /> : brick === "minimal_pairs" ? <PairConfiguration options={contrastOptions} contrastKey={contrastKey} onContrastChange={(value) => { setContrastKey(value); setSelectedIds([]); }} position={position} onPositionChange={(value) => { setPosition(value); setContrastKey(""); }} requireImages={requireImages} onRequireImagesChange={(value) => { setRequireImages(value); setSelectedIds([]); setContrastKey(""); }} automatic={mode === "automatic"} itemCount={itemCount} onCountChange={setItemCount} /> : brick === "sentence_reading" ? <SentenceReadingConfiguration audiences={sentenceAudiences} audience={sentenceAudience} itemCount={sentenceCount} automatic={mode === "automatic"} onAudienceChange={setSentenceAudience} onCountChange={setSentenceCount} /> : <PhonologyConfiguration brick={brick} phoneme={phoneme} position={position} syllables={syllables} cluster={cluster} geminate={geminate} kind={kind} itemCount={itemCount} automatic={mode === "automatic"} wordPhonemes={wordPhonemes} clusters={clusters} geminates={geminates} onPhoneme={setPhoneme} onPosition={setPosition} onSyllables={setSyllables} onCluster={setCluster} onGeminate={setGeminate} onKind={(value) => { setKind(value); setSelectedIds([]); }} onCount={setItemCount} />}</div>
        {brick !== "reading_comprehension" && mode === "manual" && <ManualBrowser items={visibleCandidates} selectedIds={selectedIds} query={query} onQuery={setQuery} getId={candidateId} onToggle={(id) => setSelectedIds((current) => toggleSelectedId(current, id))} brick={brick} />}
      </Step>
      <Step title="Controlla l’attività">{brick === "reading_comprehension" ? <ReadingPreview preview={readingPreview} shownAnswers={shownAnswers} onToggleAnswer={(id) => setShownAnswers(toggleSet(shownAnswers, id))} /> : <ActivityPreview preview={preparedPreview as ExercisePreview<Candidate>} mode={mode} selectedCount={selectedItems.length} brick={brick} showWords={showWords} showIpa={showIpa} onShowWords={setShowWords} onShowIpa={setShowIpa} />}</Step>
      {recipeNotice && <p role="status" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{recipeNotice}</p>}
      {recipeDialogOpen && <RecipeDialog name={recipeName} description={recipeDescription} onName={setRecipeName} onDescription={setRecipeDescription} onCancel={() => setRecipeDialogOpen(false)} onSave={() => void saveCurrentRecipe()} />}
      <div className="sticky bottom-0 flex flex-wrap items-center justify-between gap-4 border-t border-slate-100 bg-white/95 py-4 backdrop-blur"><p className="text-sm font-semibold text-slate-500">{preparedExercise ? `${preparedExercise.items.length} contenuti pronti` : "Scegli almeno un contenuto"}</p><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setRecipeNotice(""); setRecipeDialogOpen(true); }} className="btn btn-secondary">Salva come ricetta</button><button type="button" onClick={addCurrentActivity} disabled={!preparedExercise} className="btn btn-primary">Aggiungi alla scheda</button></div></div>
    </div>
  </FocusedWorkspace>;
}

function FocusedWorkspace({ title, onBack, children }: { title: string; onBack: () => void; children: React.ReactNode }) { return <div className="mt-8 space-y-6"><button type="button" onClick={onBack} className="inline-flex min-h-11 items-center rounded-xl px-2 text-sm font-bold text-emerald-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500">← Torna alla scheda</button><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Nuova scheda</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{title}</h2></div>{children}</div>; }
function RecipeList({ recipes, onUse, onDelete }: { recipes: ExerciseRecipeV1[]; onUse: (recipe: ExerciseRecipeV1) => void; onDelete: (id: string) => Promise<void> }) {
  const { saveExerciseRecipe } = useData();
  if (!recipes.length) return null;
  return <section className="mb-7 rounded-3xl border border-emerald-100 bg-emerald-50/50 p-4 sm:p-5"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-700">Le mie ricette</p><p className="mt-1 text-sm text-slate-600">Configurazioni personali riutilizzabili per una singola attività.</p></div><div className="grid gap-3 sm:grid-cols-2">{recipes.map((recipe) => <article key={recipe.id} className="rounded-2xl border border-emerald-100 bg-white p-4"><strong className="block text-slate-900">{recipe.name}</strong>{recipe.description && <p className="mt-1 text-sm text-slate-500">{recipe.description}</p>}<p className="mt-2 text-xs font-semibold text-emerald-700">{exerciseBricks.find((entry) => entry.code === recipe.kind)?.title}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="btn btn-primary" onClick={() => onUse(recipe)}>Usa ricetta</button><button type="button" className="btn btn-secondary" onClick={() => { const name = window.prompt("Nome della ricetta", recipe.name)?.trim(); if (!name) return; const description = window.prompt("Descrizione facoltativa", recipe.description || ""); if (description !== null) void saveExerciseRecipe({ ...recipe, name, description: description.trim() || undefined, updatedAt: new Date().toISOString() }); }}>Modifica dettagli</button><button type="button" className="btn btn-secondary" onClick={() => { if (window.confirm(`Eliminare la ricetta “${recipe.name}”?`)) void onDelete(recipe.id); }}>Elimina</button></div></article>)}</div></section>;
}
function RecipeDialog({ name, description, onName, onDescription, onCancel, onSave }: { name: string; description: string; onName: (value: string) => void; onDescription: (value: string) => void; onCancel: () => void; onSave: () => void }) {
  return <section role="dialog" aria-modal="true" aria-labelledby="recipe-dialog-title" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 sm:p-5"><h3 id="recipe-dialog-title" className="font-bold text-slate-900">Salva come ricetta</h3><div className="mt-4 grid gap-4"><label className="text-xs font-bold text-slate-600">Nome<input autoFocus className="field" maxLength={120} value={name} onChange={(event) => onName(event.target.value)} /></label><label className="text-xs font-bold text-slate-600">Descrizione facoltativa<textarea className="field min-h-20" maxLength={500} value={description} onChange={(event) => onDescription(event.target.value)} /></label></div><div className="mt-4 flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={onCancel}>Annulla</button><button type="button" className="btn btn-primary" onClick={onSave}>Salva ricetta</button></div></section>;
}
function activityDescription(code: ExerciseBrickCode) { if (code === "image_naming") return "Scegli immagini da denominare"; if (code === "minimal_pairs") return "Lavora su contrasti fonologici"; if (code === "word_nonword_repetition") return "Crea liste di parole e non-parole"; if (code === "reading_comprehension") return "Scegli un brano con domande"; return "Prepara una lista di frasi da leggere"; }

function candidateId(item: Candidate) { return "wordId" in item ? item.wordId : "minimalPairId" in item ? item.minimalPairId : "contentId" in item ? item.contentId : item.sentenceId; }
function candidateLabel(item: Candidate) { return "minimalPairId" in item ? `${item.wordA} ${item.wordB}` : item.text; }
function ModeSwitch({ value, onChange }: { value: SelectionMode; onChange: (value: SelectionMode) => void }) { return <div><p className="mb-2 text-xs font-bold text-slate-500">Come vuoi scegliere?</p><div className="inline-flex rounded-xl bg-slate-100 p-1" role="group" aria-label="Modalità di selezione"><button type="button" onClick={() => onChange("manual")} aria-pressed={value === "manual"} className={`min-h-11 rounded-lg px-4 text-sm font-bold ${value === "manual" ? "bg-white text-emerald-800 shadow-sm" : "text-slate-500"}`}>Scegli manualmente</button><button type="button" onClick={() => onChange("automatic")} aria-pressed={value === "automatic"} className={`min-h-11 rounded-lg px-4 text-sm font-bold ${value === "automatic" ? "bg-white text-emerald-800 shadow-sm" : "text-slate-500"}`}>Usa i filtri</button></div></div>; }

function ManualBrowser({ items, selectedIds, query, onQuery, getId, onToggle, brick }: { items: Candidate[]; selectedIds: string[]; query: string; onQuery: (value: string) => void; getId: (item: Candidate) => string; onToggle: (id: string) => void; brick: ExerciseBrickCode }) { return <div className="mt-6 border-t border-slate-100 pt-5"><div className="flex flex-wrap items-end justify-between gap-3"><label className="min-w-0 flex-1 text-xs font-bold text-slate-500">Cerca<input className="field" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Cerca una parola o una frase" /></label><p className="pb-3 text-sm font-bold text-violet-700">{selectedIds.length} selezionati</p></div>{!items.length ? <p className="mt-4 rounded-2xl border border-dashed border-slate-200 p-6 text-center text-sm text-slate-500">Nessun contenuto disponibile con questi criteri.</p> : <div className={`mt-4 grid max-h-[34rem] gap-3 overflow-y-auto pr-1 ${brick === "sentence_reading" ? "grid-cols-1" : "sm:grid-cols-2 lg:grid-cols-3"}`}>{items.map((item) => { const id = getId(item), selected = selectedIds.includes(id); return <button type="button" key={id} aria-pressed={selected} onClick={() => onToggle(id)} className={`rounded-2xl border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 ${selected ? "border-violet-500 bg-violet-50 ring-1 ring-violet-200" : "border-slate-200 bg-white hover:border-violet-200"}`}><CandidateCard item={item} /><span className={`mt-3 block text-xs font-bold ${selected ? "text-violet-700" : "text-slate-400"}`}>{selected ? "Selezionato" : "Seleziona"}</span></button>; })}</div>}</div>; }
function CandidateCard({ item }: { item: Candidate }) { if ("wordId" in item) return <><img src={item.imagePath} alt={item.altText} className="aspect-[4/3] w-full rounded-xl bg-slate-50 object-contain" /><strong className="mt-2 block text-center">{item.text}</strong></>; if ("minimalPairId" in item) return <><div className="grid grid-cols-2 gap-2">{[[item.imagePathA, item.wordA], [item.imagePathB, item.wordB]].map(([path, word]) => <div key={word} className="text-center">{path ? <img src={path} alt="" className="aspect-square w-full rounded-lg bg-slate-50 object-contain" /> : <div className="grid aspect-square place-items-center rounded-lg bg-slate-50 text-xs text-slate-400">solo testo</div>}<strong className="mt-1 block text-sm">{word}</strong></div>)}</div><span className="mt-2 block text-center text-xs text-slate-500">{minimalPairContrastLabel(item)}</span></>; if ("contentId" in item) return <><strong className="block text-lg text-slate-900">{item.text}</strong><span className="mt-1 block text-sm text-slate-500">{item.syllabification}</span></>; return <><strong className="block leading-6 text-slate-900">{item.text}</strong><span className="mt-1 block text-xs text-slate-400">{item.wordCount} parole</span></>; }

function PairConfiguration({ options, contrastKey, onContrastChange, position, onPositionChange, requireImages, onRequireImagesChange, automatic, itemCount, onCountChange }: { options: { key: string; label: string; count: number }[]; contrastKey: string; onContrastChange: (value: string) => void; position: string; onPositionChange: (value: string) => void; requireImages: boolean; onRequireImagesChange: (value: boolean) => void; automatic: boolean; itemCount: number; onCountChange: (value: number) => void }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-bold text-slate-500">Contrasto<select className="field" value={contrastKey} onChange={(event) => onContrastChange(event.target.value)}><option value="">Tutti i contrasti reali</option>{options.map((option) => <option key={option.key} value={option.key}>{option.label} · {option.count} {option.count === 1 ? "coppia" : "coppie"}</option>)}</select></label><Select label="Posizione" value={position} onChange={onPositionChange} options={positions.slice(1).map((x) => x.value)} labels={Object.fromEntries(positions.map((x) => [x.value, x.label]))} /><Check label="Richiedi due immagini" checked={requireImages} onChange={onRequireImagesChange} />{automatic && <Count value={itemCount} onChange={onCountChange} />}</div>; }
function PhonologyConfiguration({ brick, phoneme, position, syllables, cluster, geminate, kind, itemCount, automatic, wordPhonemes, clusters, geminates, onPhoneme, onPosition, onSyllables, onCluster, onGeminate, onKind, onCount }: { brick: ExerciseBrickCode; phoneme: string; position: string; syllables: "" | `${number}` | "4+"; cluster: string; geminate: string; kind: "word" | "nonword" | "both"; itemCount: number; automatic: boolean; wordPhonemes: string[]; clusters: string[]; geminates: string[]; onPhoneme: (value: string) => void; onPosition: (value: string) => void; onSyllables: (value: "" | `${number}` | "4+") => void; onCluster: (value: string) => void; onGeminate: (value: string) => void; onKind: (value: "word" | "nonword" | "both") => void; onCount: (value: number) => void }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Select label="Fonema" value={phoneme} onChange={onPhoneme} options={wordPhonemes} /><Select label="Posizione" value={position} onChange={onPosition} options={positions.slice(1).map((x) => x.value)} labels={Object.fromEntries(positions.map((x) => [x.value, x.label]))} /><Select label="Sillabe" value={syllables} onChange={(value) => onSyllables(value as typeof syllables)} options={["1", "2", "3", "4+"]} /><Select label="Fonema nel cluster" value={cluster} onChange={onCluster} options={clusters} /><Select label="Geminata" value={geminate} onChange={onGeminate} options={geminates} />{brick === "word_nonword_repetition" && <label className="text-xs font-bold text-slate-500">Contenuti<select value={kind} onChange={(event) => onKind(event.target.value as typeof kind)} className="field"><option value="both">Parole e non-parole</option><option value="word">Solo parole</option><option value="nonword">Solo non-parole</option></select></label>}{automatic && <Count value={itemCount} onChange={onCount} />}</div>; }
function SentenceReadingConfiguration({ audiences, audience, itemCount, automatic, onAudienceChange, onCountChange }: { audiences: string[]; audience: string; itemCount: number; automatic: boolean; onAudienceChange: (value: string) => void; onCountChange: (value: number) => void }) { return <div className="grid gap-4 sm:grid-cols-2"><Select label="Destinatario editoriale" value={audience} onChange={onAudienceChange} options={audiences} labels={audienceLabels} emptyLabel="Tutte le frasi" />{automatic && <Count value={itemCount} onChange={onCountChange} />}</div>; }
function Count({ value, onChange }: { value: number; onChange: (value: number) => void }) { return <label className="text-xs font-bold text-slate-500">Quantità<select value={value} onChange={(event) => onChange(Number(event.target.value))} className="field">{counts.map((count) => <option key={count}>{count}</option>)}</select></label>; }

const audienceLabels: Record<ContentAudience, string> = { preschool: "Età prescolare", primary_school: "Scuola primaria", secondary_school: "Scuola secondaria", adolescent: "Adolescente", adult: "Adulto", older_adult: "Adulto anziano" };
const questionLabels: Record<PassageQuestionType, string> = { literal: "Letterale", inferential: "Inferenza", sequence: "Sequenza", vocabulary: "Vocabolario" };
function ReadingConfiguration({ preview, audiences, audience, passageId, onAudienceChange, onPassageChange }: { preview: ReadingComprehensionPreview; audiences: string[]; audience: string; passageId: string; onAudienceChange: (value: string) => void; onPassageChange: (value: string) => void }) { return <div className="space-y-5"><Select label="Destinatario editoriale" value={audience} onChange={onAudienceChange} options={audiences} labels={audienceLabels} emptyLabel="Tutti i brani" /><div><p className="text-xs font-bold text-slate-500">Scegli il brano</p><div className="mt-2 grid gap-3 sm:grid-cols-2">{preview.availablePassages.map((passage) => <button key={passage.passageId} type="button" aria-pressed={passageId === passage.passageId} onClick={() => onPassageChange(passage.passageId)} className={`rounded-2xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 ${passageId === passage.passageId ? "border-violet-400 bg-violet-50" : "border-slate-200 hover:border-violet-200"}`}><strong className="block text-sm text-slate-800">{passage.title}</strong><span className="mt-2 block text-xs text-slate-500">{passage.wordCount} parole · {passage.questionCount} domande</span></button>)}</div></div></div>; }
function ReadingPreview({ preview, shownAnswers, onToggleAnswer }: { preview: ReadingComprehensionPreview; shownAnswers: Set<string>; onToggleAnswer: (id: string) => void }) { if (!preview.selectedPassage) return <p className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">Scegli un brano per visualizzare l’anteprima.</p>; const passage = preview.selectedPassage; return <article className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-5 sm:p-8"><h3 className="text-2xl font-bold text-slate-900">{passage.title}</h3><p className="mt-5 whitespace-pre-line leading-8 text-slate-700">{passage.text}</p><ol className="mt-6 space-y-4 border-t border-slate-100 pt-5">{passage.questions.map((question) => <li key={question.id} className="ml-5 list-decimal"><p className="font-semibold">{question.prompt} <span className="ml-2 text-xs text-slate-400">{questionLabels[question.type]}</span></p>{question.expectedAnswer && <><button type="button" onClick={() => onToggleAnswer(question.id)} className="mt-2 text-sm font-semibold text-violet-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400">{shownAnswers.has(question.id) ? "Nascondi risposta suggerita" : "Mostra risposta suggerita"}</button>{shownAnswers.has(question.id) && <p className="mt-2 rounded-xl bg-violet-50 p-3 text-sm">{question.expectedAnswer}</p>}</>}</li>)}</ol></article>; }

function ActivityPreview({ preview, mode, selectedCount, brick, showWords, showIpa, onShowWords, onShowIpa }: { preview: ExercisePreview<Candidate>; mode: SelectionMode; selectedCount: number; brick: ExerciseBrickCode; showWords: boolean; showIpa: boolean; onShowWords: (value: boolean) => void; onShowIpa: (value: boolean) => void }) { return <><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500"><strong className="text-slate-800">{mode === "manual" ? selectedCount : preview.items.length}</strong> contenuti pronti</p><div className="flex gap-4">{brick === "image_naming" && <Check label="Mostra parole" checked={showWords} onChange={onShowWords} />}{brick === "word_nonword_repetition" && <Check label="Mostra IPA" checked={showIpa} onChange={onShowIpa} />}</div></div><PreviewGrid preview={preview} brick={brick} showWords={showWords} showIpa={showIpa} /></>; }

function PreviewGrid({ preview, brick, showWords, showIpa }: { preview: ExercisePreview<Candidate>; brick: ExerciseBrickCode; showWords: boolean; showIpa: boolean }) { if (!preview.items.length) return <p className="mt-5 rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">Nessun contenuto selezionato.</p>; if (brick === "sentence_reading") return <ol className="mt-5 space-y-3">{preview.items.map((raw, index) => { const item = raw as SentenceReadingItem; return <li key={item.sentenceId} className="flex gap-3 rounded-2xl border border-slate-200 p-4"><span className="font-bold text-violet-600">{index + 1}.</span><p className="font-semibold leading-7">{item.text}</p></li>; })}</ol>; return <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{preview.items.map((raw) => { if (brick === "image_naming") { const item = raw as ImageNamingItem; return <Card key={item.wordId}><img src={item.imagePath} alt={item.altText} className="aspect-[4/3] w-full rounded-xl bg-slate-50 object-contain" />{showWords && <p className="mt-3 text-center font-bold">{item.text}</p>}</Card>; } if (brick === "minimal_pairs") { const item = raw as MinimalPairItem; return <Card key={item.minimalPairId}><CandidateCard item={item} /></Card>; } const item = raw as RepetitionItem; return <Card key={item.contentId}><p className="text-center text-xl font-bold">{item.text}</p><p className="mt-2 text-center text-sm text-slate-500">{item.syllabification}</p>{showIpa && <p className="mt-1 text-center text-sm text-violet-700">{item.phonemicTranscription}</p>}</Card>; })}</div>; }
function asPreview<T>(brickCode: ExerciseBrickCode, title: string, items: T[], requestedItemCount: number, total: number): ExercisePreview<T> { return { brickCode, title, items, requestedItemCount, availableItemCount: items.length, warnings: total < requestedItemCount ? [`${total} contenuti disponibili con questi criteri.`] : [] }; }
function toggleSet(current: Set<string>, id: string) { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }
function Step({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-[1.5rem] border border-slate-200 bg-white p-4 sm:p-6"><h2 className="mb-4 text-base font-bold">{title}</h2>{children}</section>; }
function Card({ children }: { children: React.ReactNode }) { return <article className="rounded-2xl border border-slate-200 bg-white p-3">{children}</article>; }
function Select({ label, value, onChange, options, labels = {}, emptyLabel = "Qualsiasi" }: { label: string; value: string; onChange: (value: string) => void; options: readonly string[]; labels?: Record<string, string>; emptyLabel?: string }) { return <label className="text-xs font-bold text-slate-500">{label}<select className="field" value={value} onChange={(event) => onChange(event.target.value)}><option value="">{emptyLabel}</option>{options.map((option) => <option key={option} value={option}>{labels[option] || `/${option}/`}</option>)}</select></label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex min-h-11 cursor-pointer items-center gap-2 text-sm font-semibold text-slate-600"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-violet-600" />{label}</label>; }
