"use client";

import { duplicateWorksheetBlock, editWorksheetDraft, moveWorksheetBlock, removeWorksheetBlock, type ExerciseBlockDraft, type WorksheetDraft } from "@/lib/exercise-lab/worksheet-draft";

export function WorksheetDraftEditor({ worksheet, onChange, onAddActivity, onEditActivity, onPreview, onSaveAsTemplate, onBrowseTemplates }: { worksheet: WorksheetDraft; onChange: (worksheet: WorksheetDraft) => void; onAddActivity: () => void; onEditActivity: (block: ExerciseBlockDraft) => void; onPreview: () => void; onSaveAsTemplate: () => void; onBrowseTemplates: () => void }) {
  const totalItems = worksheet.blocks.reduce((total, block) => total + block.exercise.items.length, 0);
  return <div className="grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_17rem]">
    <main className="min-w-0 space-y-7">
      <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Titolo della scheda<input className="field" value={worksheet.title} onChange={(event) => onChange(editWorksheetDraft(worksheet, { title: event.target.value }))} /></label><label className="text-xs font-bold text-slate-500">Istruzione generale (facoltativa)<input className="field" value={worksheet.instructions} onChange={(event) => onChange(editWorksheetDraft(worksheet, { instructions: event.target.value }))} /></label></div><div className="mt-4 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><button type="button" className="btn btn-secondary" onClick={onBrowseTemplates}>Modelli di scheda</button><button type="button" className="btn btn-quiet" onClick={onSaveAsTemplate}>Salva come modello</button></div></section>
      <section aria-labelledby="activity-list-heading"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Composizione</p><h2 id="activity-list-heading" className="mt-1 text-xl font-bold text-slate-900">Attività della scheda</h2></div><span className="shrink-0 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">{worksheet.blocks.length} attività</span></div>
        {!worksheet.blocks.length ? <div className="mt-4 rounded-3xl border border-dashed border-emerald-200 bg-emerald-50/40 px-5 py-10 text-center"><p className="text-sm text-slate-600">La scheda è ancora vuota.</p><button type="button" onClick={onAddActivity} className="btn btn-primary mt-4">+ Aggiungi attività</button></div> : <ol className="mt-4 space-y-3">{worksheet.blocks.map((block, index) => <li key={block.id}><ActivityRow block={block} index={index} total={worksheet.blocks.length} onEdit={() => onEditActivity(block)} onDuplicate={() => onChange(duplicateWorksheetBlock(worksheet, block.id))} onRemove={() => onChange(removeWorksheetBlock(worksheet, block.id))} onMove={(direction) => onChange(moveWorksheetBlock(worksheet, block.id, direction))} /></li>)}</ol>}
        {!!worksheet.blocks.length && <button type="button" onClick={onAddActivity} className="mt-4 flex min-h-14 w-full items-center justify-center rounded-2xl border border-dashed border-emerald-300 bg-white text-sm font-bold text-emerald-800 transition hover:bg-emerald-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500">+ Aggiungi attività</button>}
      </section>
      <button type="button" onClick={onPreview} disabled={!worksheet.blocks.length} className="btn btn-primary w-full disabled:cursor-not-allowed disabled:opacity-40 lg:hidden">Anteprima scheda</button>
    </main>
    <aside className="hidden lg:sticky lg:top-24 lg:block"><div className="rounded-3xl border border-emerald-100 bg-emerald-50/60 p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">La tua scheda</p><dl className="mt-5 space-y-4"><div><dt className="text-xs text-slate-500">Attività</dt><dd className="text-2xl font-bold text-slate-900">{worksheet.blocks.length}</dd></div><div><dt className="text-xs text-slate-500">Elementi totali</dt><dd className="text-2xl font-bold text-slate-900">{totalItems}</dd></div></dl><button type="button" onClick={onPreview} disabled={!worksheet.blocks.length} className="btn btn-primary mt-6 w-full disabled:cursor-not-allowed disabled:opacity-40">Anteprima scheda</button></div></aside>
  </div>;
}

function ActivityRow({ block, index, total, onEdit, onDuplicate, onRemove, onMove }: { block: ExerciseBlockDraft; index: number; total: number; onEdit: () => void; onDuplicate: () => void; onRemove: () => void; onMove: (direction: -1 | 1) => void }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 transition-colors hover:border-emerald-200 sm:p-5"><div className="flex gap-3 sm:gap-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-emerald-50 text-sm font-bold text-emerald-800">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold text-slate-900">{block.exercise.title}</h3><p className="mt-1 text-xs font-semibold text-slate-400">{block.exercise.items.length} {itemNoun(block)}</p></div><div className="flex shrink-0 items-center gap-1"><button type="button" onClick={onEdit} className="min-h-11 rounded-xl px-3 text-sm font-bold text-emerald-800 hover:bg-emerald-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500">Modifica</button><button type="button" disabled={index === 0} onClick={() => onMove(-1)} aria-label="Sposta attività su" title="Sposta su" className="grid h-11 w-11 place-items-center rounded-xl text-lg text-slate-500 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 disabled:cursor-not-allowed disabled:opacity-25">↑</button><button type="button" disabled={index === total - 1} onClick={() => onMove(1)} aria-label="Sposta attività giù" title="Sposta giù" className="grid h-11 w-11 place-items-center rounded-xl text-lg text-slate-500 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 disabled:cursor-not-allowed disabled:opacity-25">↓</button><ActivityMenu onDuplicate={onDuplicate} onRemove={onRemove} /></div></div><CompactPreview block={block} /></div></div></article>;
}

function ActivityMenu({ onDuplicate, onRemove }: { onDuplicate: () => void; onRemove: () => void }) {
  return <details className="relative"><summary aria-label="Altre azioni attività" title="Altre azioni" className="grid h-11 w-11 cursor-pointer list-none place-items-center rounded-xl text-xl font-bold leading-none text-slate-500 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 [&::-webkit-details-marker]:hidden">•••</summary><div className="absolute right-0 z-10 mt-1 min-w-40 rounded-2xl border border-slate-200 bg-white p-1.5 shadow-lg shadow-slate-900/5"><button type="button" onClick={onDuplicate} className="min-h-11 w-full rounded-xl px-3 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500">Duplica</button><button type="button" onClick={onRemove} className="min-h-11 w-full rounded-xl px-3 text-left text-sm font-semibold text-rose-700 hover:bg-rose-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-500">Elimina</button></div></details>;
}

function itemNoun(block: ExerciseBlockDraft) { if (block.exercise.kind === "picture_naming") return block.exercise.items.length === 1 ? "immagine" : "immagini"; if (block.exercise.kind === "minimal_pairs") return block.exercise.items.length === 1 ? "coppia" : "coppie"; if (block.exercise.kind === "sentence_reading") return block.exercise.items.length === 1 ? "frase" : "frasi"; return block.exercise.items.length === 1 ? "elemento" : "elementi"; }

function CompactPreview({ block }: { block: ExerciseBlockDraft }) {
  const exercise = block.exercise;
  if (!exercise.items.length) return <p className="mt-3 text-sm italic text-slate-400">Nessun contenuto</p>;
  if (exercise.kind === "picture_naming") { const shown = exercise.items.slice(0, 3); return <div className="mt-3 flex items-center gap-2">{shown.map((item) => <img key={item.wordId} src={item.imagePath} alt={item.altText} className="h-12 w-12 rounded-xl bg-slate-50 object-contain" />)}{exercise.items.length > 3 && <span className="text-sm font-bold text-slate-400">+{exercise.items.length - 3}</span>}</div>; }
  if (exercise.kind === "minimal_pairs") return <p className="mt-3 line-clamp-2 text-sm text-slate-600">{exercise.items.slice(0, 2).map((item) => `${item.wordA} ↔ ${item.wordB}`).join(" · ")}{exercise.items.length > 2 ? ` · +${exercise.items.length - 2}` : ""}</p>;
  if (exercise.kind === "repetition") return <p className="mt-3 truncate text-sm text-slate-600">{exercise.items.slice(0, 3).map((item) => item.text).join(" · ")}{exercise.items.length > 3 ? ` · +${exercise.items.length - 3}` : ""}</p>;
  if (exercise.kind === "reading_comprehension") return <p className="mt-3 text-sm text-slate-600"><span className="font-semibold">{exercise.items[0].passageTitle}</span> · {exercise.items[0].questions.length} domande</p>;
  return <p className="mt-3 truncate text-sm text-slate-600">“{exercise.items[0].text}”{exercise.items.length > 1 ? ` · +${exercise.items.length - 1} frasi` : ""}</p>;
}
