"use client";

import { ExerciseDraftEditor } from "@/components/exercise-draft-editor";
import { editWorksheetDraft, moveWorksheetBlock, removeWorksheetBlock, updateWorksheetBlock, type WorksheetDraft } from "@/lib/exercise-lab/worksheet-draft";

export function WorksheetDraftEditor({ worksheet, onChange, onAddActivity }: { worksheet: WorksheetDraft; onChange: (worksheet: WorksheetDraft) => void; onAddActivity: () => void }) {
  return <section className="rounded-[1.75rem] border border-violet-200 bg-violet-50/40 p-4 sm:p-6" aria-labelledby="worksheet-heading">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-700">Scheda in preparazione</p><h2 id="worksheet-heading" className="mt-1 text-xl font-bold text-slate-900">{worksheet.blocks.length} {worksheet.blocks.length === 1 ? "attività" : "attività"}</h2></div><button type="button" onClick={onAddActivity} className="btn btn-primary">+ Aggiungi un’altra attività</button></header>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Titolo scheda<input className="field bg-white" value={worksheet.title} onChange={(event) => onChange(editWorksheetDraft(worksheet, { title: event.target.value }))} /></label><label className="text-xs font-bold text-slate-500">Istruzione generale (facoltativa)<input className="field bg-white" value={worksheet.instructions} onChange={(event) => onChange(editWorksheetDraft(worksheet, { instructions: event.target.value }))} /></label></div>
    {!worksheet.blocks.length ? <p className="mt-5 rounded-2xl border border-dashed border-violet-200 bg-white/70 p-7 text-center text-sm text-slate-500">Scegli un Mattoncino e aggiungi la prima attività alla scheda.</p> : <ol className="mt-6 space-y-4">{worksheet.blocks.map((block, index) => <li key={block.id} className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-violet-600">Attività {index + 1}</p><h3 className="mt-1 font-bold text-slate-900">{block.exercise.title}</h3><p className="mt-1 text-sm text-slate-500">{block.exercise.items.length} {block.exercise.items.length === 1 ? "elemento" : "elementi"}</p></div><div className="flex flex-wrap justify-end gap-1"><button type="button" disabled={index === 0} onClick={() => onChange(moveWorksheetBlock(worksheet, block.id, -1))} className="min-h-11 rounded-xl px-3 text-sm font-semibold text-slate-600 hover:bg-slate-50 disabled:opacity-35">Su</button><button type="button" disabled={index === worksheet.blocks.length - 1} onClick={() => onChange(moveWorksheetBlock(worksheet, block.id, 1))} className="min-h-11 rounded-xl px-3 text-sm font-semibold text-slate-600 hover:bg-slate-50 disabled:opacity-35">Giù</button><button type="button" onClick={() => onChange(removeWorksheetBlock(worksheet, block.id))} className="min-h-11 rounded-xl px-3 text-sm font-semibold text-rose-700 hover:bg-rose-50">Elimina</button></div></div><details open className="mt-4 border-t border-slate-100 pt-4"><summary className="cursor-pointer py-2 text-sm font-bold text-violet-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400">Anteprima e modifica attività</summary><div className="mt-4"><ExerciseDraftEditor draft={block.exercise} initialDraft={block.initialExercise} onChange={(exercise) => onChange(updateWorksheetBlock(worksheet, block.id, exercise))} /></div></details></li>)}</ol>}
  </section>;
}
