import Link from "next/link";
import { ToolMonogram } from "@/components/clinical-tools/tool-directory";
import { clinicalAreaLabel, italianVersionLabel, licenseStatusLabel, primaryLink, rightsLabel, toolTypeLabel } from "@/lib/clinical-tools/search";
import type { ClinicalToolCatalogEntry } from "@/lib/clinical-tools/types";

export function ClinicalToolDetail({ tool }: { tool: ClinicalToolCatalogEntry }) {
  const link = primaryLink(tool);
  return <main>
    <Link href="/risorse/strumenti" className="inline-flex min-h-11 items-center rounded-lg text-sm font-bold text-sage-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">← Strumenti clinici</Link>
    <header className="mt-4 overflow-hidden rounded-[1.8rem] border border-sage-100 bg-gradient-to-br from-sage-50 via-white to-amber-50/50 p-5 shadow-[0_20px_50px_rgba(43,69,55,.055)] sm:p-8 lg:p-10">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start"><ToolMonogram tool={tool} large /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-white/90 px-2.5 py-1 text-xs font-bold text-sage-800 shadow-sm">{clinicalAreaLabel(tool.clinicalAreas[0])}</span><Badge tone={tool.licenseStatus === "open_verified" ? "green" : "neutral"}>{licenseStatusLabel(tool.licenseStatus)}</Badge></div><h1 className="mt-4 max-w-4xl text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">{tool.acronym || tool.name}</h1>{tool.acronym && <p className="mt-2 max-w-3xl text-base font-semibold text-slate-600 sm:text-lg">{tool.name}</p>}{tool.version && <p className="mt-1 text-sm text-slate-500">{tool.version}</p>}<p className="mt-4 text-sm font-semibold text-sage-800">{toolTypeLabel(tool.toolType)} · {tool.population.label}</p><p className="mt-4 max-w-3xl leading-7 text-slate-600">{tool.shortDescription}</p><div className="mt-6 flex flex-wrap gap-2">{link && <a href={link.href} target="_blank" rel="noopener noreferrer" className="btn btn-primary min-h-11">{link.label}</a>}{tool.rights.licenseUrl && tool.rights.licenseUrl !== link?.href && <a href={tool.rights.licenseUrl} target="_blank" rel="noopener noreferrer" className="btn btn-secondary min-h-11">Informazioni sulla licenza ↗</a>}</div></div></div>
    </header>
    <section className="mt-7 rounded-[1.5rem] border border-slate-200/90 bg-white p-5 shadow-[0_12px_35px_rgba(43,69,55,.035)] sm:p-6">
      <h2 className="text-base font-bold text-slate-900">In breve</h2>
      <div className="mt-4 grid grid-cols-2 gap-x-5 gap-y-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6"><BriefFact label="Età / popolazione" value={tool.population.label} /><BriefFact label="Tipo" value={toolTypeLabel(tool.toolType)} /><BriefFact label="Somministrazione" value={tool.administrationModes.map(humanize).join(", ")} /><BriefFact label="Lingua" value={tool.availableLanguages.join(", ")} /><BriefFact label="Versione italiana" value={italianVersionLabel(tool)} /><BriefFact label="Dati normativi" value={tool.italianValidation.normativeDataAvailable ? "Disponibili" : "Non disponibili"} /><BriefFact label="Tipo di risultato" value={humanize(tool.resultType)} /></div>
    </section>
    <section className="mt-6 rounded-[1.6rem] border border-slate-200/90 bg-white p-5 shadow-[0_12px_35px_rgba(43,69,55,.035)] sm:p-7 lg:p-8">
      <div><h2 className="text-xl font-bold text-slate-900">Panoramica</h2><p className="mt-5 text-sm leading-7 text-slate-600">{tool.shortDescription}</p><p className="mt-4 text-sm leading-7 text-slate-600">{tool.population.targetDescription}</p></div>
      <div className="my-7 border-t border-slate-100" />
      <div><h2 className="text-xl font-bold text-slate-900">Uso clinico</h2><div className="mt-5 grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3"><Definition label="Aree cliniche" value={tool.clinicalAreas.map(clinicalAreaLabel).join(", ")} /><Definition label="Modalità di somministrazione" value={tool.administrationModes.map(humanize).join(", ")} /><Definition label="Tipo di risultato" value={humanize(tool.resultType)} /></div><p className="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">Le informazioni hanno finalità descrittiva. ARMONIA non raccomanda automaticamente lo strumento e non interpreta i risultati.</p></div>
    </section>
    <div className="mt-6 grid items-stretch gap-6 lg:grid-cols-2">
      <CompactSection title="Licenza e diritti"><Definition label="Uso commerciale" value={rightsLabel(tool.rights.commercialUse)} /><Definition label="Integrazione software" value={rightsLabel(tool.rights.softwareIntegration)} /><Definition label="Redistribuzione" value={rightsLabel(tool.rights.redistribution)} /><Definition label="Modifica" value={rightsLabel(tool.rights.modification)} /><Definition label="Ultima verifica" value={formatDate(tool.rights.lastCheckedDate)} />{tool.rights.licenseUrl && <a href={tool.rights.licenseUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex min-h-11 items-center text-sm font-bold text-sage-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Informazioni sulla licenza ↗</a>}</CompactSection>
      <section className="h-full rounded-[1.4rem] border border-sage-100 bg-sage-50/60 p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.13em] text-sage-700">In ARMONIA</p><p className="mt-3 text-sm leading-6 text-slate-600">{tool.integrationStatus === "integrated" ? "Può essere somministrato direttamente dal Percorso clinico." : tool.licenseStatus === "open_verified" ? "Licenza compatibile verificata. L’integrazione nativa non è ancora disponibile." : "Puoi registrare questo strumento nel Percorso clinico e inserire manualmente risultato e note."}</p>{tool.integrationStatus !== "integrated" && <p className="mt-3 text-xs leading-5 text-slate-500">La presenza nel catalogo non equivale ad autorizzazione all’integrazione nativa.</p>}<Link href="/pazienti" className="mt-4 inline-flex min-h-11 items-center text-sm font-bold text-sage-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Apri i pazienti →</Link></section>
    </div>
  </main>;
}

const humanize = (value: string) => value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());
const formatDate = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString("it-IT", { day: "numeric", month: "long", year: "numeric" });
function Badge({ children, tone }: { children: React.ReactNode; tone: "green" | "neutral" }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${tone === "green" ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-700"}`}>{children}</span>; }
function CompactSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="h-full rounded-[1.4rem] border border-slate-200/90 bg-white p-5 sm:p-6"><h2 className="text-base font-bold text-slate-900">{title}</h2><div className="mt-4">{children}</div></section>; }
function BriefFact({ label, value }: { label: string; value?: string }) { if (!value) return null; return <div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold leading-5 text-slate-700">{value}</p></div>; }
function Definition({ label, value }: { label: string; value?: string }) { if (!value) return null; return <div className="border-b border-slate-100 py-2.5 first:pt-0 last:border-0 last:pb-0"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm leading-5 text-slate-700">{value}</p></div>; }
