import Link from "next/link";
import { ToolMonogram } from "@/components/clinical-tools/tool-directory";
import { clinicalAreaLabel, italianVersionLabel, licenseStatusLabel, primaryLink, rightsLabel, toolTypeLabel } from "@/lib/clinical-tools/search";
import type { ClinicalToolCatalogEntry } from "@/lib/clinical-tools/types";

export function ClinicalToolDetail({ tool }: { tool: ClinicalToolCatalogEntry }) {
  const link = primaryLink(tool);
  const isIddsi = tool.id === "iddsi-framework-it";
  const isArmoniaOriginal = tool.origin === "armonia";
  const iddsiResources = isIddsi ? tool.references.filter((reference) => reference.kind.startsWith("iddsi_official_")) : [];
  return <main>
    <Link href="/risorse/strumenti" className="inline-flex min-h-11 items-center rounded-lg text-sm font-bold text-sage-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">← Strumenti clinici</Link>
    <header className="mt-4 overflow-hidden rounded-[1.8rem] border border-sage-100 bg-gradient-to-br from-sage-50 via-white to-amber-50/50 p-5 shadow-[0_20px_50px_rgba(43,69,55,.055)] sm:p-8 lg:p-10">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start"><ToolMonogram tool={tool} large /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-white/90 px-2.5 py-1 text-xs font-bold text-sage-800 shadow-sm">{isIddsi ? "Deglutizione / alimentazione" : clinicalAreaLabel(tool.clinicalAreas[0])}</span><Badge tone={tool.licenseStatus === "open_verified" || isArmoniaOriginal ? "green" : "neutral"}>{licenseStatusLabel(tool.licenseStatus)}</Badge>{isArmoniaOriginal && <Badge tone="neutral">Non standardizzato</Badge>}</div><h1 className="mt-4 max-w-4xl text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">{tool.acronym || tool.name}</h1>{tool.acronym && <p className="mt-2 max-w-3xl text-base font-semibold text-slate-600 sm:text-lg">{tool.name}</p>}{tool.version && <p className="mt-1 text-sm text-slate-500">Versione {tool.version}</p>}<p className="mt-4 text-sm font-semibold text-sage-800">{toolTypeLabel(tool.toolType)} · {tool.population.label}</p><p className="mt-4 max-w-3xl leading-7 text-slate-600">{tool.shortDescription}</p><div className="mt-6 flex flex-wrap gap-2">{link && <a href={link.href} target="_blank" rel="noopener noreferrer" className="btn btn-primary min-h-11">{link.label}</a>}{tool.rights.licenseUrl && tool.rights.licenseUrl !== link?.href && <a href={tool.rights.licenseUrl} target="_blank" rel="noopener noreferrer" className="btn btn-secondary min-h-11">Informazioni sulla licenza ↗</a>}</div></div></div>
    </header>
    <section className="mt-7 rounded-[1.5rem] border border-slate-200/90 bg-white p-5 shadow-[0_12px_35px_rgba(43,69,55,.035)] sm:p-6">
      <h2 className="text-base font-bold text-slate-900">In breve</h2>
      <div className="mt-4 grid grid-cols-2 gap-x-5 gap-y-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6"><BriefFact label="Età / popolazione" value={tool.population.label} /><BriefFact label="Tipo" value={toolTypeLabel(tool.toolType)} /><BriefFact label="Somministrazione" value={tool.administrationModes.map(humanize).join(", ")} /><BriefFact label="Lingua" value={tool.availableLanguages.join(", ")} /><BriefFact label="Versione italiana" value={italianVersionLabel(tool)} /><BriefFact label="Dati normativi" value={tool.italianValidation.normativeDataAvailable ? "Disponibili" : "Non disponibili"} /><BriefFact label="Tipo di risultato" value={humanize(tool.resultType)} /></div>
    </section>
    {isIddsi && <>
      <section className="mt-6 grid gap-4 rounded-[1.5rem] border border-amber-100 bg-amber-50/40 p-5 sm:grid-cols-2 sm:p-6">
        <div><h2 className="text-base font-bold text-slate-900">Che cos’è</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600"><li>Uno standard di classificazione delle consistenze.</li><li>Una terminologia condivisa per alimenti e bevande.</li><li>Un insieme di metodi pratici di verifica.</li></ul></div>
        <div><h2 className="text-base font-bold text-slate-900">Che cosa non fa</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600"><li>Non diagnostica la disfagia.</li><li>Non prescrive automaticamente una dieta.</li><li>Non determina autonomamente la consistenza adatta al paziente.</li><li>Non sostituisce la valutazione clinica.</li></ul></div>
      </section>
      <section className="mt-6 rounded-[1.5rem] border border-sage-100 bg-white p-5 shadow-[0_12px_35px_rgba(43,69,55,.035)] sm:p-6">
        <h2 className="text-lg font-bold text-slate-900">Materiali ufficiali IDDSI in italiano</h2><p className="mt-2 text-sm leading-6 text-slate-600">I documenti restano ospitati e aggiornati da International Dysphagia Diet Standardisation Initiative.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{iddsiResources.map((resource) => <a key={resource.kind} href={resource.url} target="_blank" rel="noopener noreferrer" className="flex min-h-14 items-center justify-between gap-3 rounded-xl border border-sage-100 bg-sage-50/50 px-4 py-3 text-sage-800 transition hover:border-sage-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500"><span><span className="block text-sm font-bold">{resource.title}</span><span className="mt-1 block text-xs font-semibold text-slate-500">Apri sul sito ufficiale IDDSI</span></span><span aria-hidden="true">↗</span></a>)}</div>
      </section>
    </>}
    {isArmoniaOriginal && tool.materials && <section className="mt-6 rounded-[1.5rem] border border-sage-100 bg-white p-5 shadow-[0_12px_35px_rgba(43,69,55,.035)] sm:p-6">
      <div className="max-w-3xl"><h2 className="text-lg font-bold text-slate-900">Materiali dello strumento</h2><p className="mt-2 text-sm leading-6 text-slate-600">Consulta o scarica i documenti originali ARMONIA. I file sono disponibili esclusivamente dopo l’accesso all’app.</p></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2">{tool.materials.filter((material) => material.kind !== "zip").map((material) => <div key={material.id} className="flex min-w-0 items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50/60 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-800">{material.label}</p><p className="mt-1 text-xs text-slate-500">{material.kind.toUpperCase()}{material.pageCount ? ` · ${material.pageCount} pagine` : ""}</p></div><div className="flex shrink-0 gap-1">{material.kind === "pdf" && <a href={materialUrl(tool.id, material.id)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center rounded-lg px-3 text-xs font-bold text-sage-700 hover:bg-sage-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Apri</a>}<a href={materialUrl(tool.id, material.id, true)} className="inline-flex min-h-11 items-center rounded-lg px-3 text-xs font-bold text-sage-700 hover:bg-sage-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Scarica</a></div></div>)}</div>
      {tool.materials.filter((material) => material.kind === "zip").map((material) => <a key={material.id} href={materialUrl(tool.id, material.id, true)} className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-sage-700 px-4 text-sm font-bold text-white transition hover:bg-sage-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500 focus-visible:ring-offset-2">Scarica pacchetto completo</a>)}
    </section>}
    <section className="mt-6 rounded-[1.6rem] border border-slate-200/90 bg-white p-5 shadow-[0_12px_35px_rgba(43,69,55,.035)] sm:p-7 lg:p-8">
      <div><h2 className="text-xl font-bold text-slate-900">Panoramica</h2><p className="mt-5 text-sm leading-7 text-slate-600">{tool.shortDescription}</p><p className="mt-4 text-sm leading-7 text-slate-600">{tool.population.targetDescription}</p></div>
      <div className="my-7 border-t border-slate-100" />
      <div><h2 className="text-xl font-bold text-slate-900">Uso clinico</h2><div className="mt-5 grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3"><Definition label="Aree cliniche" value={tool.clinicalAreas.map(clinicalAreaLabel).join(", ")} /><Definition label="Modalità di somministrazione" value={tool.administrationModes.map(humanize).join(", ")} /><Definition label="Tipo di risultato" value={humanize(tool.resultType)} /></div><p className="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">Le informazioni hanno finalità descrittiva. ARMONIA non raccomanda automaticamente lo strumento e non interpreta i risultati.</p></div>
    </section>
    <div className="mt-6 grid items-stretch gap-6 lg:grid-cols-2">
      {isArmoniaOriginal ? <CompactSection title="Stato editoriale e accesso"><Definition label="Origine" value="Strumento originale ARMONIA" /><Definition label="Standardizzazione" value="Non standardizzato" /><Definition label="Accesso" value="Materiali disponibili agli utenti autenticati" /><Definition label="Versione" value={tool.version || undefined} />{tool.editorialNotice && <p className="mt-4 rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-950">{tool.editorialNotice}</p>}</CompactSection> : <CompactSection title="Licenza e diritti">{isIddsi && <Definition label="Attribuzione" value="International Dysphagia Diet Standardisation Initiative" />}<Definition label="Uso commerciale" value={rightsLabel(tool.rights.commercialUse)} /><Definition label="Integrazione software" value={rightsLabel(tool.rights.softwareIntegration)} /><Definition label="Redistribuzione" value={rightsLabel(tool.rights.redistribution)} /><Definition label="Modifica" value={rightsLabel(tool.rights.modification)} /><Definition label="Ultima verifica" value={formatDate(tool.rights.lastCheckedDate)} />{tool.rights.licenseUrl && <a href={tool.rights.licenseUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex min-h-11 items-center text-sm font-bold text-sage-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Informazioni sulla licenza ↗</a>}</CompactSection>}
      <section className="h-full rounded-[1.4rem] border border-sage-100 bg-sage-50/60 p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.13em] text-sage-700">In ARMONIA</p><p className="mt-3 text-sm leading-6 text-slate-600">{isArmoniaOriginal ? "Puoi consultare e scaricare i materiali professionali. Lo strumento non dispone di compilazione nativa o interpretazione automatica." : tool.integrationStatus === "integrated" ? "Può essere somministrato direttamente dal Percorso clinico." : tool.licenseStatus === "open_verified" ? "Licenza compatibile verificata. L’integrazione nativa non è ancora disponibile." : "Puoi registrare questo strumento nel Percorso clinico e inserire manualmente risultato e note."}</p>{tool.integrationStatus !== "integrated" && !isArmoniaOriginal && <p className="mt-3 text-xs leading-5 text-slate-500">La presenza nel catalogo non equivale ad autorizzazione all’integrazione nativa.</p>}<Link href="/pazienti" className="mt-4 inline-flex min-h-11 items-center text-sm font-bold text-sage-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sage-500">Apri i pazienti →</Link></section>
    </div>
  </main>;
}

const humanize = (value: string) => value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());
const materialUrl = (toolId: string, materialId: string, download = false) => `/api/clinical-tools/${encodeURIComponent(toolId)}/materials/${encodeURIComponent(materialId)}${download ? "?download=1" : ""}`;
const formatDate = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString("it-IT", { day: "numeric", month: "long", year: "numeric" });
function Badge({ children, tone }: { children: React.ReactNode; tone: "green" | "neutral" }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${tone === "green" ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-700"}`}>{children}</span>; }
function CompactSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="h-full rounded-[1.4rem] border border-slate-200/90 bg-white p-5 sm:p-6"><h2 className="text-base font-bold text-slate-900">{title}</h2><div className="mt-4">{children}</div></section>; }
function BriefFact({ label, value }: { label: string; value?: string }) { if (!value) return null; return <div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold leading-5 text-slate-700">{value}</p></div>; }
function Definition({ label, value }: { label: string; value?: string }) { if (!value) return null; return <div className="border-b border-slate-100 py-2.5 first:pt-0 last:border-0 last:pb-0"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm leading-5 text-slate-700">{value}</p></div>; }
