"use client";

import { useState } from "react";
import type { LanguageOralModuleV1, LanguageOralObservationStatus, LanguageOralScreeningStatus } from "@/lib/clinical/assessment-v2";
import { LANGUAGE_ORAL_EARLY_LABELS, LANGUAGE_ORAL_LABELS, LANGUAGE_ORAL_OPTIONS, LANGUAGE_ORAL_PRODUCTION_LABELS } from "@/lib/clinical/module-registry";

type Props = { value: LanguageOralModuleV1; readOnly: boolean; onChange: (value: LanguageOralModuleV1) => void };
type Domain = { status: LanguageOralObservationStatus; notes?: string };

export function LanguageOralEditor({ value, readOnly, onChange }: Props) {
  const setDomain = <K extends keyof LanguageOralModuleV1>(key: K, domain: LanguageOralModuleV1[K]) => {
    if (domain === undefined) { const { [key]: _removed, ...rest } = value; onChange(rest); }
    else onChange({ ...value, [key]: domain });
  };
  return <div className="space-y-4">
    <DomainCard title="Sviluppo comunicativo-linguistico precoce" description="Osservazioni attuali sulle modalità comunicative precoci. Le informazioni anamnestiche restano separate." detailsSubtitle="Aspetti esplorati, caratteristiche osservate e note" value={value.earlyCommunication} readOnly={readOnly} onChange={(v) => setDomain("earlyCommunication", v)}>{(v, patch) => <><ChipGroup label="Aspetti esplorati" values={v.observedAreas || []} options={LANGUAGE_ORAL_OPTIONS.earlyCommunicationAreas} labels={LANGUAGE_ORAL_EARLY_LABELS} readOnly={readOnly} onChange={(items) => patch({ observedAreas: items.length ? items : undefined })} /><ChipGroup label="Caratteristiche osservate" values={v.observedFeatures || []} options={LANGUAGE_ORAL_OPTIONS.earlyCommunicationFeatures} readOnly={readOnly} onChange={(items) => patch({ observedFeatures: items.length ? items : undefined })} /><Notes label="Osservazioni sullo sviluppo comunicativo precoce" value={v.notes} readOnly={readOnly} onChange={(notes) => patch({ notes })} /></>}</DomainCard>
    <DomainCard title="Comprensione linguistica" description="Capacità recettiva globale a diversi livelli di complessità." detailsSubtitle="Livelli esplorati, fattori di difficoltà, facilitazioni e note" value={value.comprehension} readOnly={readOnly} onChange={(v) => setDomain("comprehension", v)}>{(v, patch) => <><ChipGroup label="Livelli di comprensione esplorati" values={v.exploredLevels || []} options={LANGUAGE_ORAL_OPTIONS.exploredLevels} readOnly={readOnly} onChange={(items) => patch({ exploredLevels: items.length ? items : undefined })} /><ChipGroup label="Osservazioni associate a maggiore difficoltà" description="Indica condizioni nelle quali la difficoltà è risultata più evidente, senza attribuire cause diagnostiche." values={v.difficultyFactors || []} options={LANGUAGE_ORAL_OPTIONS.difficultyFactors} readOnly={readOnly} onChange={(items) => patch({ difficultyFactors: items.length ? items : undefined })} /><ChipGroup label="Facilitazioni osservate" values={v.facilitations || []} options={LANGUAGE_ORAL_OPTIONS.facilitations} readOnly={readOnly} onChange={(items) => patch({ facilitations: items.length ? items : undefined })} /><Notes label="Osservazioni sulla comprensione" value={v.notes} readOnly={readOnly} onChange={(notes) => patch({ notes })} /></>}</DomainCard>
    <DomainCard title="Produzione linguistica" description="Caratteristiche globali dell’output linguistico nel contesto osservato." detailsSubtitle="Livello prevalente, iniziativa, quantità, formulazione e note" value={value.production} readOnly={readOnly} onChange={(v) => setDomain("production", v)}>{(v, patch) => <><SingleChoice label="Livello prevalente della produzione" value={v.outputLevel} options={LANGUAGE_ORAL_OPTIONS.outputLevels} labels={LANGUAGE_ORAL_PRODUCTION_LABELS} readOnly={readOnly} onChange={(outputLevel) => patch({ outputLevel })} /><SingleChoice label="Iniziativa comunicativo-verbale" value={v.initiative} options={LANGUAGE_ORAL_OPTIONS.initiatives} readOnly={readOnly} onChange={(initiative) => patch({ initiative })} /><SingleChoice label="Quantità dell’output verbale" value={v.verbalOutputAmount} options={LANGUAGE_ORAL_OPTIONS.outputAmounts} readOnly={readOnly} onChange={(verbalOutputAmount) => patch({ verbalOutputAmount })} /><ChipGroup label="Formulazione globale del messaggio" values={v.formulation || []} options={LANGUAGE_ORAL_OPTIONS.formulationFeatures} readOnly={readOnly} onChange={(items) => patch({ formulation: items.length ? items : undefined })} /><Notes label="Osservazioni sulla produzione" value={v.notes} readOnly={readOnly} onChange={(notes) => patch({ notes })} /></>}</DomainCard>
    <DomainCard title="Lessico-semantica" description="Accesso, selezione e organizzazione lessicale e semantica." detailsSubtitle="Aspetti esplorati, caratteristiche osservate e note" value={value.lexicalSemantics} readOnly={readOnly} onChange={(v) => setDomain("lexicalSemantics", v)}>{(v, patch) => <><ChipGroup label="Aspetti esplorati" values={v.observedAreas || []} options={LANGUAGE_ORAL_OPTIONS.lexicalAreas} readOnly={readOnly} onChange={(items) => patch({ observedAreas: items.length ? items : undefined })} /><ChipGroup label="Caratteristiche osservate" values={v.observedFeatures || []} options={LANGUAGE_ORAL_OPTIONS.lexicalFeatures} readOnly={readOnly} onChange={(items) => patch({ observedFeatures: items.length ? items : undefined })} /><Notes label="Osservazioni lessico-semantiche" value={v.notes} readOnly={readOnly} onChange={(notes) => patch({ notes })} /></>}</DomainCard>
    <DomainCard title="Morfosintassi" description="Organizzazione morfologica e sintattica dell’enunciato." detailsSubtitle="Aspetti esplorati, caratteristiche osservate e note" value={value.morphosyntax} readOnly={readOnly} onChange={(v) => setDomain("morphosyntax", v)}>{(v, patch) => <><ChipGroup label="Aspetti esplorati" values={v.observedAreas || []} options={LANGUAGE_ORAL_OPTIONS.morphosyntaxAreas} readOnly={readOnly} onChange={(items) => patch({ observedAreas: items.length ? items : undefined })} /><ChipGroup label="Caratteristiche osservate" values={v.observedFeatures || []} options={LANGUAGE_ORAL_OPTIONS.morphosyntaxFeatures} readOnly={readOnly} onChange={(items) => patch({ observedFeatures: items.length ? items : undefined })} /><Notes label="Osservazioni morfosintattiche" value={v.notes} readOnly={readOnly} onChange={(notes) => patch({ notes })} /></>}</DomainCard>
    <DomainCard title="Discorso e narrazione" description="Organizzazione sovrafrasale del messaggio, del discorso e del racconto." detailsSubtitle="Contesti esplorati, caratteristiche osservate e note" value={value.discourseNarrative} readOnly={readOnly} onChange={(v) => setDomain("discourseNarrative", v)}>{(v, patch) => <><ChipGroup label="Contesti esplorati" values={v.contextsExplored || []} options={LANGUAGE_ORAL_OPTIONS.discourseContexts} readOnly={readOnly} onChange={(items) => patch({ contextsExplored: items.length ? items : undefined })} /><ChipGroup label="Caratteristiche osservate" values={v.observedFeatures || []} options={LANGUAGE_ORAL_OPTIONS.discourseFeatures} readOnly={readOnly} onChange={(items) => patch({ observedFeatures: items.length ? items : undefined })} /><Notes label="Osservazioni su discorso e narrazione" value={v.notes} readOnly={readOnly} onChange={(notes) => patch({ notes })} /></>}</DomainCard>
    <section className="rounded-2xl border border-sage-100 bg-sage-50/50 p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-wide text-sage-700">Possibili approfondimenti</p><p className="mt-2 text-sm leading-6 text-slate-500">Segnalazioni rapide e non diagnostiche. Non attivano automaticamente altre aree della valutazione.</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><ScreeningCard title="Intelligibilità del parlato" value={value.intelligibilityScreening} readOnly={readOnly} suggestion="Può essere utile approfondire nell’area Fonetica, fonologia e articolazione o Disturbi motori del parlato." onChange={(v) => setDomain("intelligibilityScreening", v)} /><ScreeningCard title="Comunicazione sociale e pragmatica" value={value.socialCommunicationScreening} readOnly={readOnly} suggestion="Può essere utile approfondire nell’area Comunicazione sociale e pragmatica." onChange={(v) => setDomain("socialCommunicationScreening", v)} /></div></section>
    <section className="rounded-2xl border border-sage-100 bg-white p-5 sm:p-6"><label className="block text-sm font-bold">Nota conclusiva sul linguaggio orale<textarea disabled={readOnly} value={value.finalNote || ""} onChange={(event) => setDomain("finalNote", event.target.value || undefined)} placeholder="Facoltativa" className="mt-2 min-h-28 w-full rounded-xl border border-sage-100 bg-white px-3 py-2.5 font-normal outline-none focus:border-sage-500 disabled:bg-slate-50" /></label><p className="mt-2 text-xs leading-5 text-slate-500">Considerazione complessiva limitata al modulo Linguaggio orale; non sostituisce la sintesi clinica generale.</p></section>
  </div>;
}

function DomainCard<T extends Domain>({ title, description, detailsSubtitle, value, readOnly, onChange, children }: { title: string; description: string; detailsSubtitle: string; value?: T; readOnly: boolean; onChange: (value?: T) => void; children: (value: T, patch: (change: Partial<T>) => void) => React.ReactNode }) {
  const [expanded, setExpanded] = useState(false);
  const patch = (change: Partial<T>) => value && onChange({ ...value, ...change });
  const detailsId = `language-oral-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-details`;
  return <section className="rounded-2xl border border-sage-100 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-sage-700">Linguaggio orale</p><h2 className="mt-1 text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div>{value && !readOnly && <button type="button" onClick={() => { onChange(undefined); setExpanded(false); }} className="text-sm font-bold text-red-600">Resetta</button>}</div><fieldset disabled={readOnly} className="mt-6"><legend className="text-sm font-bold">Osservazione generale</legend><div className="mt-3 grid gap-2 lg:grid-cols-3">{LANGUAGE_ORAL_OPTIONS.statuses.map((status) => <button type="button" key={status} aria-pressed={value?.status === status} onClick={() => onChange({ ...value, status } as T)} className={`rounded-xl border px-4 py-3 text-left text-sm ${value?.status === status ? "border-sage-500 bg-sage-100 font-bold text-sage-700" : "border-sage-100 bg-white text-slate-600"}`}>{LANGUAGE_ORAL_LABELS[status]}</button>)}</div></fieldset>{value ? <div className="mt-5 overflow-hidden rounded-xl border border-sage-100 bg-sage-50/60"><button type="button" onClick={() => setExpanded((current) => !current)} className="flex w-full items-center justify-between gap-4 px-4 py-3.5 text-left transition-colors hover:bg-sage-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-sage-500" aria-expanded={expanded} aria-controls={detailsId}><span><span className="block text-sm font-bold text-ink">Dettagli facoltativi</span><span className="mt-1 block text-xs leading-5 text-slate-500">{detailsSubtitle}</span></span><Chevron open={expanded} /></button>{expanded && <div id={detailsId} className="space-y-6 border-t border-sage-100 bg-white px-4 py-5 sm:px-5">{children(value, patch)}</div>}</div> : <p className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-500">Non documentato. Seleziona uno stato soltanto quando vuoi registrare un’osservazione.</p>}</section>;
}

function Chevron({ open }: { open: boolean }) { return <svg aria-hidden="true" viewBox="0 0 20 20" fill="none" className="h-5 w-5 shrink-0 text-sage-700"><path d={open ? "m5 12.5 5-5 5 5" : "m5 7.5 5 5 5-5"} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function Notes({ label, value, readOnly, onChange }: { label: string; value?: string; readOnly: boolean; onChange: (value?: string) => void }) { return <label className="block text-sm font-bold">{label}<textarea disabled={readOnly} value={value || ""} onChange={(event) => onChange(event.target.value || undefined)} className="mt-2 min-h-28 w-full rounded-xl border border-sage-100 bg-white px-3 py-2.5 font-normal outline-none focus:border-sage-500 disabled:bg-slate-50" /></label>; }
function SingleChoice<T extends string>({ label, value, options, labels = LANGUAGE_ORAL_LABELS, readOnly, onChange }: { label: string; value?: T; options: readonly T[]; labels?: Record<string, string>; readOnly: boolean; onChange: (value?: T) => void }) { return <fieldset disabled={readOnly}><legend className="text-sm font-bold">{label}</legend><div className="mt-3 flex flex-wrap gap-2">{options.map((option) => <button type="button" key={option} aria-pressed={value === option} onClick={() => onChange(value === option ? undefined : option)} className={`rounded-full border px-3 py-2 text-sm ${value === option ? "border-sage-500 bg-sage-100 font-bold text-sage-700" : "border-sage-100 bg-white text-slate-600"}`}>{labels[option]}</button>)}</div></fieldset>; }
function ChipGroup<T extends string>({ label, description, values, options, labels = LANGUAGE_ORAL_LABELS, readOnly, onChange }: { label: string; description?: string; values: T[]; options: readonly T[]; labels?: Record<string, string>; readOnly: boolean; onChange: (values: T[]) => void }) { return <fieldset disabled={readOnly}><legend className="text-sm font-bold">{label}</legend>{description && <p className="mt-1 text-xs leading-5 text-slate-500">{description}</p>}<div className="mt-3 flex flex-wrap gap-2">{options.map((option) => { const selected = values.includes(option); return <button type="button" key={option} aria-pressed={selected} onClick={() => onChange(selected ? values.filter((item) => item !== option) : [...values, option])} className={`rounded-full border px-3 py-2 text-sm ${selected ? "border-sage-500 bg-sage-100 font-bold text-sage-700" : "border-sage-100 bg-white text-slate-600"}`}>{labels[option]}</button>; })}</div></fieldset>; }

function ScreeningCard({ title, value, suggestion, readOnly, onChange }: { title: string; value?: { status: LanguageOralScreeningStatus; notes?: string }; suggestion: string; readOnly: boolean; onChange: (value?: { status: LanguageOralScreeningStatus; notes?: string }) => void }) {
  const showSuggestion = value?.status === "further_assessment" || value?.status === "concern_observed";
  return <div className="rounded-xl border border-sage-100 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-xs text-slate-500">Segnalazione rapida</p></div>{value && !readOnly && <button type="button" onClick={() => onChange(undefined)} className="text-xs font-bold text-red-600">Resetta</button>}</div><fieldset disabled={readOnly} className="mt-4"><div className="space-y-2">{LANGUAGE_ORAL_OPTIONS.screeningStatuses.map((status) => <button type="button" key={status} aria-pressed={value?.status === status} onClick={() => onChange({ ...value, status })} className={`w-full rounded-lg border px-3 py-2.5 text-left text-sm ${value?.status === status ? "border-sage-500 bg-sage-100 font-bold text-sage-700" : "border-sage-100 text-slate-600"}`}>{LANGUAGE_ORAL_LABELS[status]}</button>)}</div></fieldset>{showSuggestion && <p className="mt-3 rounded-lg bg-sage-50 px-3 py-2 text-xs leading-5 text-sage-700">{suggestion}</p>}{value && <label className="mt-4 block text-xs font-bold">Nota facoltativa<textarea disabled={readOnly} value={value.notes || ""} onChange={(event) => onChange({ ...value, notes: event.target.value || undefined })} className="mt-2 min-h-20 w-full rounded-lg border border-sage-100 px-3 py-2 font-normal outline-none focus:border-sage-500 disabled:bg-slate-50" /></label>}</div>;
}
