"use client";

import { useState } from "react";
import type { ClinicalObservationStatus, FluencyModuleV1, SpeechSoundModuleV1, VoiceModuleV1 } from "@/lib/clinical/assessment-v2";
import { LANGUAGE_ORAL_LABELS, LANGUAGE_ORAL_OPTIONS, OBSERVATIONAL_MODULE_LABELS, OBSERVATIONAL_MODULE_OPTIONS } from "@/lib/clinical/module-registry";

type Profile = { status: ClinicalObservationStatus; notes?: string } & Record<string, string[] | string | undefined>;
type Config = { title: string; noteLabel: string; groups: { key: string; label: string; options: readonly string[] }[] };
const toggleCode = (values: string[], code: string) => { const next = values.includes(code) ? values.filter((item) => item !== code) : [...values, code]; return next.length ? next : undefined; };

function ObservationalModuleEditor({ value, readOnly, onChange, config }: { value: { profile?: Profile }; readOnly: boolean; onChange: (value: { profile?: Profile }) => void; config: Config }) {
  const [expanded, setExpanded] = useState(false);
  const profile = value.profile;
  const setProfile = (next?: Profile) => next ? onChange({ profile: next }) : onChange({});
  const patch = (change: Partial<Profile>) => profile && setProfile({ ...profile, ...change });
  return <section className="rounded-2xl border border-sage-100 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-sage-700">Area clinica</p><h2 className="mt-1 text-xl font-bold">{config.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">Panoramica osservazionale rapida con approfondimenti facoltativi.</p></div>{profile && !readOnly && <button type="button" onClick={() => { setProfile(undefined); setExpanded(false); }} className="text-sm font-bold text-red-600">Resetta</button>}</div>
    <fieldset disabled={readOnly} className="mt-6"><legend className="text-sm font-bold">Osservazione generale</legend><div className="mt-3 grid gap-2 lg:grid-cols-3">{LANGUAGE_ORAL_OPTIONS.statuses.map((status) => <button type="button" key={status} aria-pressed={profile?.status === status} onClick={() => setProfile({ ...profile, status })} className={`rounded-xl border px-4 py-3 text-left text-sm ${profile?.status === status ? "border-sage-500 bg-sage-100 font-bold text-sage-700" : "border-sage-100 bg-white text-slate-600"}`}>{LANGUAGE_ORAL_LABELS[status]}</button>)}</div></fieldset>
    {profile ? <div className="mt-5 overflow-hidden rounded-xl border border-sage-100 bg-sage-50/60"><button type="button" onClick={() => setExpanded((current) => !current)} className="flex w-full items-center justify-between gap-4 px-4 py-3.5 text-left"><span><span className="block text-sm font-bold">Dettagli facoltativi</span><span className="mt-1 block text-xs text-slate-500">Aspetti esplorati, caratteristiche osservate e note</span></span><span aria-hidden="true" className="text-sage-700">{expanded ? "⌃" : "⌄"}</span></button>{expanded && <div className="space-y-6 border-t border-sage-100 bg-white px-4 py-5">{config.groups.map((group) => { const selected = Array.isArray(profile[group.key]) ? profile[group.key] as string[] : []; return <fieldset disabled={readOnly} key={group.key}><legend className="text-sm font-bold">{group.label}</legend><div className="mt-3 flex flex-wrap gap-2">{group.options.map((option) => { const active = selected.includes(option); return <button type="button" key={option} aria-pressed={active} onClick={() => patch({ [group.key]: toggleCode(selected, option) })} className={`rounded-full border px-3 py-2 text-sm ${active ? "border-sage-500 bg-sage-100 font-bold text-sage-700" : "border-sage-100 text-slate-600"}`}>{OBSERVATIONAL_MODULE_LABELS[option]}</button>; })}</div></fieldset>; })}<label className="block text-sm font-bold">{config.noteLabel}<textarea disabled={readOnly} value={profile.notes || ""} onChange={(event) => patch({ notes: event.target.value || undefined })} className="mt-2 min-h-24 w-full rounded-xl border border-sage-100 px-3 py-2 font-normal outline-none focus:border-sage-500 disabled:bg-slate-50" /></label></div>}</div> : <p className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-500">Non documentato. Seleziona uno stato soltanto quando vuoi registrare un’osservazione.</p>}
  </section>;
}

export function SpeechSoundEditor({ value, readOnly, onChange }: { value: SpeechSoundModuleV1; readOnly: boolean; onChange: (value: SpeechSoundModuleV1) => void }) { return <ObservationalModuleEditor value={value as { profile?: Profile }} readOnly={readOnly} onChange={(next) => onChange(next as SpeechSoundModuleV1)} config={{ title: "Fonetica, fonologia e articolazione", noteLabel: "Osservazioni su fonetica, fonologia e articolazione", groups: [{ key: "exploredAreas", label: "Aspetti esplorati", options: OBSERVATIONAL_MODULE_OPTIONS.speechSound.exploredAreas }, { key: "observedFeatures", label: "Caratteristiche osservate", options: OBSERVATIONAL_MODULE_OPTIONS.speechSound.observedFeatures }] }} />; }
export function FluencyEditor({ value, readOnly, onChange }: { value: FluencyModuleV1; readOnly: boolean; onChange: (value: FluencyModuleV1) => void }) { return <ObservationalModuleEditor value={value as { profile?: Profile }} readOnly={readOnly} onChange={(next) => onChange(next as FluencyModuleV1)} config={{ title: "Fluenza", noteLabel: "Osservazioni sulla fluenza", groups: [{ key: "contextsExplored", label: "Contesti esplorati", options: OBSERVATIONAL_MODULE_OPTIONS.fluency.contextsExplored }, { key: "observedFeatures", label: "Caratteristiche della fluenza osservate", options: OBSERVATIONAL_MODULE_OPTIONS.fluency.observedFeatures }, { key: "associatedFeatures", label: "Caratteristiche associate", options: OBSERVATIONAL_MODULE_OPTIONS.fluency.associatedFeatures }] }} />; }
export function VoiceEditor({ value, readOnly, onChange }: { value: VoiceModuleV1; readOnly: boolean; onChange: (value: VoiceModuleV1) => void }) { return <ObservationalModuleEditor value={value as { profile?: Profile }} readOnly={readOnly} onChange={(next) => onChange(next as VoiceModuleV1)} config={{ title: "Voce", noteLabel: "Osservazioni sulla voce", groups: [{ key: "contextsExplored", label: "Contesti esplorati", options: OBSERVATIONAL_MODULE_OPTIONS.voice.contextsExplored }, { key: "exploredAspects", label: "Aspetti esplorati", options: OBSERVATIONAL_MODULE_OPTIONS.voice.exploredAspects }, { key: "observedFeatures", label: "Caratteristiche osservate", options: OBSERVATIONAL_MODULE_OPTIONS.voice.observedFeatures }] }} />; }
