"use client";

import { useEffect, useState } from "react";
import { Modal } from "@/components/modal";
import { QAB_ITALIAN_ATTRIBUTION, getQabItalianForm } from "@/lib/clinical-tools/qab-it/content";
import { QAB_SECTION_LABELS, getQabCardForItem, getQabScoreLabel, getQabSectionGuide, type QabSectionGuide } from "@/lib/clinical-tools/qab-it/guidance";
import { scoreQabItalian } from "@/lib/clinical-tools/qab-it/scoring";
import { QAB_SECTION_CODES, type QabAdministrationV1, type QabForm, type QabItemResponse, type QabScore, type QabSectionCode } from "@/lib/clinical-tools/qab-it/types";
import { QabResults } from "./qab-results";
import { QabStimulusView } from "./qab-stimulus-view";

export function QabRunner({ value, readOnly, onChange, onClose }: { value: QabAdministrationV1; readOnly: boolean; onChange: (value: QabAdministrationV1) => void; onClose: () => void }) {
  const [welcomed, setWelcomed] = useState(false);
  const [sectionCode, setSectionCode] = useState<QabSectionCode>("awareness");
  const [itemIndex, setItemIndex] = useState(0);
  const [introduced, setIntroduced] = useState<ReadonlySet<QabSectionCode>>(() => new Set());
  const [guideOpen, setGuideOpen] = useState(false);
  const [stimulusOpen, setStimulusOpen] = useState(false);
  const [resetOpen, setResetOpen] = useState(false);
  const [stopCandidate, setStopCandidate] = useState<{ itemId: string; score: QabScore; reason: string }>();
  const [completionMessage, setCompletionMessage] = useState("");
  const definition = value.form ? getQabItalianForm(value.form) : undefined;
  const section = definition?.sections[sectionCode];
  const item = section?.items[itemIndex];
  const card = value.form ? getQabCardForItem(value.form, sectionCode, itemIndex) : undefined;
  const guide = value.form ? getQabSectionGuide(value.form, sectionCode) : undefined;
  const resultMode = value.status === "completed" || value.status === "stopped";
  const total = definition ? Object.values(definition.sections).reduce((sum, entry) => sum + entry.items.length, 0) : 0;

  const setResponse = (response: QabItemResponse) => {
    if (!item || readOnly || resultMode) return;
    if (response.status === "scored" && item.stopRule?.scores.includes(response.score)) {
      setStopCandidate({ itemId: item.id, score: response.score, reason: item.stopRule.reason });
      return;
    }
    onChange({ ...value, status: "in_progress", responses: { ...value.responses, [item.id]: response } });
  };
  const confirmStop = () => {
    if (!stopCandidate) return;
    onChange({ ...value, status: "stopped", responses: { ...value.responses, [stopCandidate.itemId]: { status: "scored", score: stopCandidate.score } }, stop: { itemId: stopCandidate.itemId, reason: stopCandidate.reason, stoppedAt: new Date().toISOString() } });
    setStopCandidate(undefined);
  };
  const complete = () => {
    const result = scoreQabItalian(value);
    if (result.status !== "available") {
      setCompletionMessage(`Somministrazione incompleta${result.status === "incomplete" && result.missingItemIds?.length ? `: ${result.missingItemIds.length} item da completare.` : "."}`);
      return;
    }
    onChange({ ...value, status: "completed" });
  };

  if (!definition && !welcomed) return <RunnerShell onClose={onClose}><Welcome onStart={() => setWelcomed(true)} /></RunnerShell>;
  if (!definition) return <RunnerShell onClose={onClose}><div className="mx-auto max-w-3xl py-8"><Eyebrow>Italian QAB</Eyebrow><h2 className="mt-2 text-3xl font-bold">Scegli il modulo</h2><p className="mt-3 text-sm leading-6 text-slate-600">I tre moduli hanno struttura e punteggio equivalenti. Cambiano gli stimoli: non sono livelli di difficoltà.</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{([1, 2, 3] as const).map((form) => <button key={form} type="button" disabled={readOnly} onClick={() => onChange({ ...value, form, status: "in_progress", administrationDate: value.administrationDate || new Date().toISOString().slice(0, 10) })} className="min-h-28 rounded-2xl border border-sage-200 bg-white p-5 text-left font-bold shadow-sm outline-none hover:border-sage-500 focus-visible:ring-2 focus-visible:ring-sage-500">Modulo {form}<span className="mt-2 block text-sm font-normal text-slate-500">Forma parallela · 8 sezioni</span></button>)}</div><Attribution /></div></RunnerShell>;

  const response = item ? value.responses[item.id] : undefined;
  return <RunnerShell onClose={onClose}>
    <header className="border-b border-sage-100 pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Eyebrow>Italian QAB · Modulo {value.form}</Eyebrow><h2 className="mt-1 text-2xl font-bold">{resultMode ? "Risultati" : QAB_SECTION_LABELS[sectionCode]}</h2>{!readOnly && !resultMode && <button type="button" onClick={() => setResetOpen(true)} className="mt-2 text-xs font-bold text-sage-700 underline">Cambia modulo / ricomincia</button>}</div><div className="text-right text-xs text-slate-500"><p>{Object.keys(value.responses).length} / {total} item registrati</p><p className="mt-1">{readOnly ? "Sola lettura" : "Autosave della valutazione attivo"}</p></div></div></header>
    {resultMode ? <div className="mx-auto mt-6 max-w-3xl"><p className="mb-4 text-sm font-semibold">Stato: {value.status === "completed" ? "Completata" : "Interrotta"}</p>{value.stop && <p className="mb-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{value.stop.reason}</p>}<QabResults value={value}/><Attribution/></div> : <>
      <nav aria-label="Sezioni QAB" className="mt-4 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="flex min-w-max gap-2">{QAB_SECTION_CODES.map((code, index) => <button key={code} type="button" onClick={() => { setSectionCode(code); setItemIndex(0); }} aria-current={sectionCode === code ? "step" : undefined} className={`min-h-11 rounded-full border px-3 text-sm font-bold outline-none focus-visible:ring-2 focus-visible:ring-sage-500 ${sectionCode === code ? "border-sage-600 bg-sage-700 text-white" : "border-sage-100 bg-white text-slate-600"}`}>{index + 1}. {QAB_SECTION_LABELS[code]}</button>)}</div></nav>
      {!introduced.has(sectionCode) && guide ? <SectionIntro code={sectionCode} guide={guide} onStart={() => setIntroduced((current) => new Set([...current, sectionCode]))}/> : <div className="mt-4 grid gap-5 lg:grid-cols-[minmax(0,1fr)_18rem]">
        <section className="rounded-2xl border border-sage-100 bg-white p-4 sm:p-6">
          <div className="flex flex-wrap items-center justify-between gap-3"><div><Eyebrow>Sezione {QAB_SECTION_CODES.indexOf(sectionCode) + 1} di 8</Eyebrow><p className="mt-1 text-sm font-bold text-sage-700">Item {itemIndex + 1} di {section?.items.length}</p></div><button type="button" onClick={() => setGuideOpen(true)} className="btn btn-quiet min-h-11 text-sm">Guida alla somministrazione</button></div>
          <div className="mt-5 rounded-2xl bg-sage-50 p-4"><Eyebrow>Cosa dire / fare</Eyebrow>{sectionCode === "spontaneousSpeech" && <Spontaneous form={value.form!} prompts={section?.prompts || []}/>} {sectionCode === "motorSpeech" && <Motor prompts={section?.prompts || []}/>}<p className="mt-3 text-lg font-semibold leading-7">{item?.prompt || item?.label}</p>{item?.prompt && <p className="mt-2 text-sm text-slate-500">{item.label}</p>}{item?.target && <div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm"><strong>Target per il professionista:</strong> {item.target}</div>}{item?.expectedAnswer && <p className="mt-3 text-sm font-semibold">Risposta attesa: {item.expectedAnswer === "yes" ? "Sì" : "No"}</p>}{item?.followUpPrompts?.length ? <ul className="mt-3 list-disc pl-5 text-sm text-slate-600">{item.followUpPrompts.map((prompt, index) => <li key={`${item.id}:follow-up:${index}`}>{prompt}</li>)}</ul> : null}</div>
          {card && <div className="mt-4 rounded-2xl border border-sage-100 p-4"><Eyebrow>Stimolo visivo</Eyebrow><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">Carta {card.cardNumber}</p><p className="text-sm text-slate-500">{card.purpose}</p></div><button type="button" onClick={() => setStimulusOpen(true)} className="btn btn-primary min-h-11 text-sm">Mostra al paziente · Carta {card.cardNumber}</button></div></div>}
          <QabTimer/>
          {item?.dynamicFields?.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{item.dynamicFields.map((field, index) => <label key={`${item.id}:dynamic:${field.key}:${index}`} className="text-sm font-bold">{field.label}<input disabled={readOnly} type={field.kind === "number" ? "number" : "text"} value={value.dynamicValues?.[`${item.id}:${field.key}`] ?? ""} onChange={(event) => onChange({ ...value, dynamicValues: { ...value.dynamicValues, [`${item.id}:${field.key}`]: field.kind === "number" ? Number(event.target.value) : event.target.value } })} className="mt-2 w-full rounded-xl border border-sage-100 px-3 py-2.5"/></label>)}</div> : null}
          <details className="mt-5 rounded-xl border border-sage-100"><summary className="cursor-pointer px-4 py-3 text-sm font-bold outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-sage-500">Risposta osservata / note qualitative</summary><div className="border-t border-sage-100 p-4"><textarea disabled={readOnly} value={response?.responseNote || ""} onChange={(event) => setResponse(response?.status === "scored" ? { ...response, responseNote: event.target.value || undefined } : { status: "notAdministered", responseNote: event.target.value || undefined })} className="min-h-24 w-full rounded-xl border border-sage-100 p-3"/></div></details>
          <div className="mt-5 border-t border-sage-100 pt-5"><p className="text-sm font-bold">Assegna il punteggio</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{item?.allowedScores.map((score) => { const stop = item.stopRule?.scores.includes(score); const selected = response?.status === "scored" && response.score === score; return <button key={score} type="button" disabled={readOnly} aria-pressed={selected} onClick={() => setResponse({ status: "scored", score, responseNote: response?.responseNote })} className={`min-h-14 rounded-xl border px-4 py-2 text-left outline-none focus-visible:ring-2 focus-visible:ring-sage-500 ${selected ? "border-sage-600 bg-sage-700 text-white" : stop ? "border-amber-300 bg-amber-50" : "border-sage-200 bg-white"}`}><b>{score}</b><span className="ml-2 text-sm font-semibold">{getQabScoreLabel(sectionCode, item, score)}</span>{stop && <small className="mt-1 block">Questo valore attiva la regola di interruzione.</small>}</button>; })}</div></div>
          <div className="mt-6 flex justify-between gap-3"><button type="button" disabled={itemIndex === 0} onClick={() => setItemIndex((i) => i - 1)} className="btn btn-quiet">Precedente</button><button type="button" disabled={!section || itemIndex >= section.items.length - 1} onClick={() => setItemIndex((i) => i + 1)} className="btn btn-primary">Successivo</button></div>
        </section>
        <aside className="space-y-4"><AdminMeta value={value} readOnly={readOnly} onChange={onChange}/><button type="button" disabled={readOnly} onClick={complete} className="btn btn-primary w-full">Completa somministrazione</button>{completionMessage && <p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{completionMessage}</p>}</aside>
      </div>}
    </>}
    {guideOpen && guide && <Modal title={`Guida · ${QAB_SECTION_LABELS[sectionCode]}`} onClose={() => setGuideOpen(false)}><Guide guide={guide}/><div className="mt-6 flex justify-end"><button type="button" onClick={() => setGuideOpen(false)} className="btn btn-primary">Torna alla somministrazione</button></div></Modal>}
    {stimulusOpen && card && <QabStimulusView card={card} onClose={() => setStimulusOpen(false)}/>} 
    {stopCandidate && <Modal title="Interrompere la somministrazione?" onClose={() => setStopCandidate(undefined)}><p className="text-sm leading-6 text-slate-600">Il punteggio selezionato attiva la regola clinica: {stopCandidate.reason}</p><p className="mt-3 text-sm text-slate-600">Le risposte restano conservate e non sarà calcolato un punteggio finale.</p><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setStopCandidate(undefined)} className="btn btn-quiet">Annulla</button><button type="button" onClick={confirmStop} className="btn btn-primary">Conferma interruzione</button></div></Modal>}
    {resetOpen && <Modal title="Cambiare modulo?" onClose={() => setResetOpen(false)}><p className="text-sm leading-6 text-slate-600">Cambiare modulo eliminerà i dati della somministrazione QAB corrente.</p><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => setResetOpen(false)} className="btn btn-quiet">Annulla</button><button type="button" onClick={() => { onChange({ kind: "qab-it", schemaVersion: 1, status: "not_started", responses: {} }); setResetOpen(false); }} className="btn bg-red-600 text-white">Cambia modulo e ricomincia</button></div></Modal>}
  </RunnerShell>;
}

function Welcome({ onStart }: { onStart: () => void }) { return <div className="mx-auto max-w-3xl py-8"><Eyebrow>Italian QAB</Eyebrow><h2 className="mt-2 text-3xl font-bold">Prima di iniziare</h2><p className="mt-4 leading-7 text-slate-600">Tre forme parallele, equivalenti per struttura e scoring, con stimoli differenti. La somministrazione dura indicativamente 15 minuti e comprende 8 sezioni.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info title="Tempi" text="Risposta senza latenza entro 3 secondi; latenza tra 3 e 6; finestra conclusa a 6 secondi."/><Info title="Responsabilità clinica" text="ARMONIA guida la sequenza, ma osservazione e punteggio restano al professionista."/><Info title="Somministrazione" text="Consegne, stimoli, note e punteggio sono presentati nello stesso flusso."/><Info title="Vista paziente" text="Le carte si aprono senza controlli o informazioni cliniche."/></div><div className="mt-7 flex justify-end"><button type="button" onClick={onStart} className="btn btn-primary">Scegli il modulo</button></div><Attribution/></div>; }
function Info({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-sage-100 bg-white p-4"><b>{title}</b><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div>; }
function SectionIntro({ code, guide, onStart }: { code: QabSectionCode; guide: QabSectionGuide; onStart: () => void }) { return <section className="mx-auto mt-5 max-w-4xl rounded-3xl border border-sage-100 bg-white p-5 sm:p-8"><Eyebrow>Sezione {QAB_SECTION_CODES.indexOf(code) + 1} di 8</Eyebrow><h3 className="mt-2 text-2xl font-bold">{QAB_SECTION_LABELS[code]}</h3><p className="mt-2 text-sm text-slate-500">Come si somministra</p><div className="mt-6"><Guide guide={guide}/></div><div className="mt-7 flex justify-end"><button type="button" onClick={onStart} className="btn btn-primary">Inizia la sezione</button></div></section>; }
function Guide({ guide }: { guide: QabSectionGuide }) { const blocks = [["Cosa fai", guide.do], ["Cosa dici", guide.say], ["Cosa mostri", guide.show], ["Come assegni il punteggio", guide.scoring], ["Note ed eccezioni", guide.notes]] as const; return <div className="grid gap-4 sm:grid-cols-2">{blocks.map(([title, entries]) => <section key={title} className="rounded-2xl bg-sage-50 p-4"><Eyebrow>{title}</Eyebrow><ul className="mt-2 space-y-2 text-sm leading-6 text-slate-700">{entries.map((entry, index) => <li key={`${title}:${index}`}>{entry}</li>)}</ul></section>)}</div>; }
function Spontaneous({ form, prompts }: { form: QabForm; prompts: readonly string[] }) { return <details className="mt-3 rounded-xl border border-sage-100 bg-white"><summary className="cursor-pointer px-4 py-3 text-sm font-bold">Le 3 fasi dell’eloquio spontaneo</summary><div className="border-t p-4 text-sm leading-6"><p><b>1.</b> Conversazione di almeno tre minuti. <b>2.</b> Descrizione della Carta 1 del Modulo {form}. <b>3.</b> Valutazione delle 10 dimensioni.</p><p className="mt-2 text-slate-600">{prompts.slice(0, 12).join(" · ")}</p></div></details>; }
function Motor({ prompts }: { prompts: readonly string[] }) { return <div className="mt-3 rounded-xl border border-sage-100 bg-white p-4"><b className="text-sm">Prima esegui i 5 compiti</b><ol className="mt-2 list-decimal pl-5 text-sm text-slate-600">{prompts.map((prompt, index) => <li key={`motor:${index}`}>{prompt}</li>)}</ol><p className="mt-2 text-sm font-semibold">Poi valuta Disartria e Aprassia articolatoria.</p></div>; }
function AdminMeta({ value, readOnly, onChange }: { value: QabAdministrationV1; readOnly: boolean; onChange: (value: QabAdministrationV1) => void }) { return <div className="rounded-2xl border border-sage-100 bg-white p-4"><Eyebrow>Somministrazione</Eyebrow>{([["Data", "administrationDate", "date"], ["Luogo", "location", "text"], ["Esaminatore", "examiner", "text"]] as const).map(([label, key, type]) => <label key={key} className="mt-3 block text-sm font-bold">{label}<input type={type} disabled={readOnly} value={value[key] || ""} onChange={(event) => onChange({ ...value, [key]: event.target.value || undefined })} className="mt-2 w-full rounded-xl border border-sage-100 px-3 py-2.5"/></label>)}</div>; }
function QabTimer() { const [elapsed, setElapsed] = useState(0); const [running, setRunning] = useState(false); useEffect(() => { if (!running) return; const started = Date.now() - elapsed * 1000; const id = window.setInterval(() => setElapsed(Math.floor((Date.now() - started) / 1000)), 100); return () => window.clearInterval(id); }, [elapsed, running]); const label = elapsed < 3 ? "Risposta senza latenza" : elapsed < 6 ? "Latenza" : "Finestra conclusa"; return <div className="mt-4 rounded-2xl border border-sage-100 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Eyebrow>Timer visivo</Eyebrow><p className="mt-1 text-3xl font-black tabular-nums">{elapsed}s</p><p className="text-sm font-semibold text-slate-600">{label}</p></div><div className="flex gap-2"><button type="button" onClick={() => setRunning((v) => !v)} className="btn btn-quiet">{running ? "Ferma" : "Avvia"}</button><button type="button" onClick={() => { setRunning(false); setElapsed(0); }} className="btn btn-quiet">Reset</button></div></div><p className="mt-2 text-xs text-slate-500">Ausilio visivo: non assegna punteggi e non viene salvato.</p></div>; }
function RunnerShell({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape" && document.querySelectorAll('[role="dialog"]').length === 1) onClose(); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [onClose]); return <div role="dialog" aria-modal="true" aria-label="Somministrazione Italian QAB" className="fixed inset-0 z-50 overflow-y-auto bg-slate-50"><div className="mx-auto min-h-full max-w-7xl p-3 pb-10 sm:p-6"><div className="flex justify-end"><button type="button" onClick={onClose} className="btn btn-quiet min-h-11">Chiudi somministrazione</button></div><main className="mt-3">{children}</main></div></div>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-xs font-bold uppercase tracking-wide text-sage-700">{children}</p>; }
function Attribution() { return <p className="mt-8 border-t border-sage-100 pt-4 text-xs leading-5 text-slate-500">{QAB_ITALIAN_ATTRIBUTION.title} · adattamento: {QAB_ITALIAN_ATTRIBUTION.adaptationAuthors.join(", ")} · {QAB_ITALIAN_ATTRIBUTION.publisher} · {QAB_ITALIAN_ATTRIBUTION.license}</p>; }
