import { getAvailableRepresentations, getContentsByType } from "./catalog.ts";

const table = (rows: [string, number][]) => ["| Voce | Conteggio |", "|---|---:|", ...rows.map(([key,value])=>`| ${key} | ${value} |`)].join("\n");
const counts = (values: string[]) => [...new Set(values)].sort((a,b)=>a.localeCompare(b,"it")).map((value)=>[value,values.filter((item)=>item===value).length] as [string,number]);

export function buildContentCoverageReport() {
  const words=getContentsByType("word"), pairs=getContentsByType("minimal_pair"), nonwords=getContentsByType("nonword"), sentences=getContentsByType("sentence"), passages=getContentsByType("passage"), sequences=getContentsByType("sequence");
  const images=words.filter((word)=>getAvailableRepresentations(word.id).image);
  const phonemes=words.flatMap((word)=>word.phonemes.map((entry)=>entry.symbol));
  const visualByPhoneme=[...new Set(phonemes)].map((symbol)=>[symbol,images.filter((word)=>word.phonemes.some((entry)=>entry.symbol===symbol)).length] as [string,number]).sort((a,b)=>a[1]-b[1]||a[0].localeCompare(b[0]));
  const pairLabels=pairs.map((pair)=>pair.contrast.kind==="phoneme"?`/${pair.contrast.phonemeA}/ ↔ /${pair.contrast.phonemeB}/`:`/${pair.contrast.segment}/ singleton ↔ geminata`);
  return `# Coverage Banca Contenuti V1\n\nReport editoriale deterministico sul catalogo reale. Non attribuisce età di acquisizione, punteggi clinici o valore normativo.\n\n## Word\n\n${table([["Totale",words.length],["Con immagine",images.length],["Senza immagine",words.length-images.length],["Reviewed",words.filter(x=>x.reviewStatus==="reviewed").length],["Draft",words.filter(x=>x.reviewStatus==="draft").length]])}\n\n### Parti del discorso\n\n${table(counts(words.map(x=>x.partOfSpeech)))}\n\n### Numero di sillabe\n\n${table(counts(words.map(x=>String(x.syllableCount))))}\n\n### Fonemi\n\n${table(counts(phonemes))}\n\n### Fonema + posizione\n\n${table(counts(words.flatMap(x=>x.phonemes.map(p=>`/${p.symbol}/ — ${p.position}`))))}\n\n### Cluster\n\n${table(counts(words.flatMap(x=>x.consonantClusters.map(c=>`/${c.phonemes.join("")}/ — ${c.position}`))))}\n\n### Geminate\n\n${table(counts(words.flatMap(x=>x.geminates.map(g=>`/${g}/`))))}\n\n### Copertura visiva più scarsa per fonema\n\n${table(visualByPhoneme.filter(([,value])=>value<=3))}\n\nLe combinazioni più povere sono i fonemi con 0–3 parole illustrate e i cluster/geminate rappresentati da un solo lemma. Questi conteggi guidano la revisione editoriale, non descrivono priorità cliniche.\n\n## Minimal pairs\n\n${table([["Totale",pairs.length],["Minimal",pairs.filter(x=>x.pairType==="minimal").length],["Near-minimal",pairs.filter(x=>x.pairType==="near_minimal").length],["Con entrambe le immagini",pairs.filter(x=>getAvailableRepresentations(x.wordAId).image&&getAvailableRepresentations(x.wordBId).image).length],["Contrasti fonemici",pairs.filter(x=>x.contrast.kind==="phoneme").length],["Contrasti di geminazione",pairs.filter(x=>x.contrast.kind==="gemination").length]])}\n\n### Contrasti\n\n${table(counts(pairLabels))}\n\n### Posizione\n\n${table(counts(pairs.map(x=>x.contrast.position)))}\n\n## Nonword\n\n${table([["Totale",nonwords.length],...counts(nonwords.map(x=>`${x.syllableCount} sillabe`))])}\n\nTarget dichiarati: ${[...new Set(nonwords.flatMap(x=>x.phonemes.map(p=>`/${p.symbol}/`)))].sort().join(", ")}.\n\n## Sentence / Passage / Sequence\n\n${table([["Frasi",sentences.length],["Brani",passages.length],["Sequenze",sequences.length]])}\n\n> Per espandere SequenceContent servono asset visivi dedicati a scene e sequenze narrative.\n`;
}
