-- Owner/patient integrity for the four legacy relations. No data repair or RLS changes.
-- Requires PostgreSQL >= 15 and patients_user_id_id_key (migration 006).
begin;
set local lock_timeout = '5s';

alter table public.appointments
  add constraint appointments_user_patient_id_key unique (user_id, patient_id, id);

-- Appointments' new UNIQUE and sessions_user_patient_id_key (020) already
-- index patient lookups. Goals needs this prefix; 033 indexes session/appointment.
create index goals_user_patient_idx on public.goals (user_id, patient_id);

alter table public.appointments
  add constraint appointments_patient_owner_fk
  foreign key (user_id, patient_id) references public.patients (user_id, id)
  on update no action on delete cascade not valid;
alter table public.goals
  add constraint goals_patient_owner_fk
  foreign key (user_id, patient_id) references public.patients (user_id, id)
  on update no action on delete cascade not valid;
alter table public.sessions
  add constraint sessions_patient_owner_fk
  foreign key (user_id, patient_id) references public.patients (user_id, id)
  on update no action on delete cascade not valid,
  add constraint sessions_appointment_owner_patient_fk
  foreign key (user_id, patient_id, appointment_id)
  references public.appointments (user_id, patient_id, id)
  match simple on update no action on delete set null (appointment_id) not valid;

alter table public.appointments validate constraint appointments_patient_owner_fk;
alter table public.goals validate constraint goals_patient_owner_fk;
alter table public.sessions validate constraint sessions_patient_owner_fk;
alter table public.sessions validate constraint sessions_appointment_owner_patient_fk;

-- Names generated by 001; confirm these in the live preflight before applying.
-- Keep all original constraints until every new FK has validated successfully.
alter table public.appointments drop constraint appointments_patient_id_fkey;
alter table public.goals drop constraint goals_patient_id_fkey;
alter table public.sessions
  drop constraint sessions_patient_id_fkey,
  drop constraint sessions_appointment_id_fkey;
commit;
