import type {SupabaseClient,User} from "@supabase/supabase-js";
import type {AppData,Appointment,AppointmentLocation,AppointmentService,EconomicDocument,EconomicDocumentLine,Goal,Material,Patient,PatientAdministrativeDetails,Payment,PaymentAllocation,ProfessionalDocumentDetails,Profile,Session} from "../types.ts";
import type {CreatePaymentInput} from "../payments.ts";
import {parseExerciseRecipeV1,type ExerciseRecipeV1} from "../exercise-lab/recipes.ts";
import {parseWorksheetTemplateV1,type WorksheetTemplateV1} from "../exercise-lab/worksheet-templates.ts";
import {parsePatientWorksheetV1,type PatientWorksheetV1} from "../exercise-lab/patient-worksheets.ts";
import {loadCloudClinicalData} from "./clinical-repository.ts";

const splitDate=(value:string)=>{const d=new Date(value);return {date:d.toLocaleDateString("sv-SE"),time:d.toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit",hour12:false})}};
const joinDate=(date:string,time:string)=>new Date(`${date}T${time}:00`).toISOString();
const check=<T extends {error:unknown}>(result:T)=>{if(result.error)throw result.error;return result};

export async function loadCloudData(client:SupabaseClient,user:User):Promise<AppData>{
  const [profiles,patients,patientAdministrativeDetails,professionalDocumentDetails,economicDocuments,economicDocumentLines,exerciseRecipes,worksheetTemplates,patientWorksheets,appointments,locations,services,sessions,payments,paymentAllocations,goals,materials,patientMaterials,sessionMaterials,sessionGoals,clinical]=await Promise.all([
    client.from("profiles").select("*").eq("id",user.id).maybeSingle(),
    client.from("patients").select("*").order("created_at",{ascending:false}),
    client.from("patient_administrative_details").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),
    client.from("professional_document_details").select("*").eq("user_id",user.id).maybeSingle(),
    client.from("economic_documents").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),
    client.from("economic_document_lines").select("*").eq("user_id",user.id).order("position"),
    client.from("exercise_recipes").select("*").eq("user_id",user.id).order("updated_at",{ascending:false}),
    client.from("worksheet_templates").select("*").eq("user_id",user.id).order("updated_at",{ascending:false}),
    client.from("patient_worksheets").select("*").eq("user_id",user.id).order("updated_at",{ascending:false}),
    client.from("appointments").select("*").order("starts_at"),
    client.from("appointment_locations").select("*").eq("user_id",user.id).order("display_order").order("name"),
    client.from("appointment_services").select("*").eq("user_id",user.id).order("display_order").order("name"),
    client.from("sessions").select("*").order("occurred_at",{ascending:false}),
    client.from("payments").select("*").eq("user_id",user.id).order("paid_at",{ascending:false}),
    client.from("payment_allocations").select("user_id,patient_id,payment_id,session_id,amount_cents,created_at").eq("user_id",user.id),
    client.from("goals").select("*").order("created_at",{ascending:false}),
    client.from("materials").select("*").order("created_at",{ascending:false}),
    client.from("patient_materials").select("patient_id,material_id"),
    client.from("session_materials").select("session_id,material_id"),
    client.from("session_goals").select("session_id,goal_id"),
    loadCloudClinicalData(client,user.id),
  ]);
  [profiles,patients,patientAdministrativeDetails,professionalDocumentDetails,economicDocuments,economicDocumentLines,exerciseRecipes,worksheetTemplates,patientWorksheets,appointments,locations,services,sessions,payments,paymentAllocations,goals,materials,patientMaterials,sessionMaterials,sessionGoals].forEach(check);
  const profileRow=profiles.data;
  const profile:Profile={firstName:profileRow?.first_name||"",lastName:profileRow?.last_name||"",profession:profileRow?.profession||"Logopedista",email:profileRow?.email||user.email||"",studio:profileRow?.studio||"",calendarColorMode:profileRow?.calendar_color_mode==="service"?"service":"location",onboardingCompletedAt:profileRow?.onboarding_completed_at??null};
  return {
    profile,
    patients:(patients.data||[]).map((p):Patient=>({id:p.id,firstName:p.first_name,lastName:p.last_name,birthDate:p.birth_date||"",contact:p.phone||"",guardian:p.guardian_name||"",school:p.school||"",schoolClass:p.school_class||"",referralReason:p.referral_reason||"",notes:p.notes||"",status:p.status,createdAt:p.created_at})),
    patientAdministrativeDetails:(patientAdministrativeDetails.data||[]).map(patientAdministrativeDetailsFromRow),
    professionalDocumentDetails:professionalDocumentDetails.data ? professionalDocumentDetailsFromRow(professionalDocumentDetails.data) : undefined,
    economicDocuments:(economicDocuments.data||[]).map(economicDocumentFromRow),
    economicDocumentLines:(economicDocumentLines.data||[]).map(economicDocumentLineFromRow),
    exerciseRecipes:(exerciseRecipes.data||[]).map(exerciseRecipeFromRow),
    worksheetTemplates:(worksheetTemplates.data||[]).map(worksheetTemplateFromRow),
    patientWorksheets:(patientWorksheets.data||[]).map(patientWorksheetFromRow),
    appointments:(appointments.data||[]).map(appointmentFromRow),
    locations:(locations.data||[]).map(appointmentLocationFromRow),
    services:(services.data||[]).map(appointmentServiceFromRow),
    sessions:(sessions.data||[]).map((s):Session=>sessionFromRow(s,(sessionGoals.data||[]).filter(x=>x.session_id===s.id).map(x=>x.goal_id),(sessionMaterials.data||[]).filter(x=>x.session_id===s.id).map(x=>x.material_id))),
    payments:(payments.data||[]).map(paymentFromRow),
    paymentAllocations:(paymentAllocations.data||[]).map(paymentAllocationFromRow),
    goals:(goals.data||[]).map(goalFromRow),
    materials:(materials.data||[]).map((m):Material=>({id:m.id,title:m.title,description:m.description||"",category:m.category||"altro",tags:m.tags||[],fileName:m.file_name||"",storagePath:m.storage_path||undefined,mimeType:m.mime_type||"",size:Number(m.file_size||0),externalUrl:m.external_url||undefined,favorite:m.is_favorite||false,patientIds:(patientMaterials.data||[]).filter(x=>x.material_id===m.id).map(x=>x.patient_id),createdAt:m.created_at})),
    clinicalPathways:clinical.clinicalPathways,
    clinicalAssessments:clinical.clinicalAssessments,
  };
}

export const exerciseRecipeFromRow=(row:{id:string;schema_version:number;kind:string;name:string;description?:string|null;configuration:unknown;created_at:string;updated_at:string})=>parseExerciseRecipeV1({id:row.id,schemaVersion:row.schema_version,kind:row.kind,name:row.name,description:row.description||undefined,configuration:row.configuration,createdAt:row.created_at,updatedAt:row.updated_at});
export const exerciseRecipeRow=(recipe:ExerciseRecipeV1,userId:string)=>({id:recipe.id,user_id:userId,schema_version:recipe.schemaVersion,kind:recipe.kind,name:recipe.name,description:recipe.description||null,configuration:recipe.configuration,created_at:recipe.createdAt,updated_at:recipe.updatedAt});
export async function listExerciseRecipes(client:SupabaseClient,userId:string){const result=check(await client.from("exercise_recipes").select("*").eq("user_id",userId).order("updated_at",{ascending:false}));return (result.data||[]).map(exerciseRecipeFromRow)}
export async function getExerciseRecipe(client:SupabaseClient,userId:string,id:string){const result=check(await client.from("exercise_recipes").select("*").eq("user_id",userId).eq("id",id).maybeSingle());return result.data?exerciseRecipeFromRow(result.data):undefined}
export async function saveExerciseRecipe(client:SupabaseClient,userId:string,recipe:ExerciseRecipeV1){const validated=parseExerciseRecipeV1(recipe);check(await client.from("exercise_recipes").upsert(exerciseRecipeRow(validated,userId)).select("id").single())}
export async function deleteExerciseRecipe(client:SupabaseClient,userId:string,id:string){check(await client.from("exercise_recipes").delete().eq("user_id",userId).eq("id",id).select("id").single())}
export const worksheetTemplateFromRow=(row:{id:string;schema_version:number;name:string;description?:string|null;template_data:unknown;created_at:string;updated_at:string})=>parseWorksheetTemplateV1({...row.template_data as object,id:row.id,schemaVersion:row.schema_version,name:row.name,description:row.description||undefined,createdAt:row.created_at,updatedAt:row.updated_at});
export const worksheetTemplateRow=(template:WorksheetTemplateV1,userId:string)=>({id:template.id,user_id:userId,schema_version:template.schemaVersion,name:template.name,description:template.description||null,template_data:{worksheetTitle:template.worksheetTitle,worksheetInstructions:template.worksheetInstructions,blocks:template.blocks},created_at:template.createdAt,updated_at:template.updatedAt});
export async function listWorksheetTemplates(client:SupabaseClient,userId:string){const result=check(await client.from("worksheet_templates").select("*").eq("user_id",userId).order("updated_at",{ascending:false}));return (result.data||[]).map(worksheetTemplateFromRow)}
export async function getWorksheetTemplate(client:SupabaseClient,userId:string,id:string){const result=check(await client.from("worksheet_templates").select("*").eq("user_id",userId).eq("id",id).maybeSingle());return result.data?worksheetTemplateFromRow(result.data):undefined}
export async function createWorksheetTemplate(client:SupabaseClient,userId:string,template:WorksheetTemplateV1){const validated=parseWorksheetTemplateV1(template);check(await client.from("worksheet_templates").insert(worksheetTemplateRow(validated,userId)).select("id").single())}
export async function updateWorksheetTemplate(client:SupabaseClient,userId:string,template:WorksheetTemplateV1){const validated=parseWorksheetTemplateV1(template);const row=worksheetTemplateRow(validated,userId);check(await client.from("worksheet_templates").update({name:row.name,description:row.description,template_data:row.template_data,updated_at:row.updated_at}).eq("user_id",userId).eq("id",template.id).select("id").single())}
export async function deleteWorksheetTemplate(client:SupabaseClient,userId:string,id:string){check(await client.from("worksheet_templates").delete().eq("user_id",userId).eq("id",id).select("id").single())}
export const patientWorksheetFromRow=(row:{id:string;patient_id:string;schema_version:number;title:string;worksheet_snapshot:unknown;assigned_home_at?:string|null;created_at:string;updated_at:string})=>parsePatientWorksheetV1({id:row.id,patientId:row.patient_id,schemaVersion:row.schema_version,title:row.title,worksheetSnapshot:row.worksheet_snapshot,assignedHomeAt:row.assigned_home_at??null,createdAt:row.created_at,updatedAt:row.updated_at});
export const patientWorksheetRow=(worksheet:PatientWorksheetV1,userId:string)=>({id:worksheet.id,user_id:userId,patient_id:worksheet.patientId,schema_version:worksheet.schemaVersion,title:worksheet.title,worksheet_snapshot:worksheet.worksheetSnapshot,assigned_home_at:worksheet.assignedHomeAt,created_at:worksheet.createdAt,updated_at:worksheet.updatedAt});
export async function listPatientWorksheets(client:SupabaseClient,userId:string,patientId:string){const result=check(await client.from("patient_worksheets").select("*").eq("user_id",userId).eq("patient_id",patientId).order("updated_at",{ascending:false}));return (result.data||[]).map(patientWorksheetFromRow)}
export async function getPatientWorksheet(client:SupabaseClient,userId:string,id:string){const result=check(await client.from("patient_worksheets").select("*").eq("user_id",userId).eq("id",id).maybeSingle());return result.data?patientWorksheetFromRow(result.data):undefined}
export async function createPatientWorksheet(client:SupabaseClient,userId:string,worksheet:PatientWorksheetV1){const validated=parsePatientWorksheetV1(worksheet);check(await client.from("patient_worksheets").insert(patientWorksheetRow(validated,userId)).select("id").single())}
export async function updatePatientWorksheet(client:SupabaseClient,userId:string,worksheet:PatientWorksheetV1){const validated=parsePatientWorksheetV1(worksheet);const row=patientWorksheetRow(validated,userId);check(await client.from("patient_worksheets").update({title:row.title,worksheet_snapshot:row.worksheet_snapshot,assigned_home_at:row.assigned_home_at,updated_at:row.updated_at}).eq("user_id",userId).eq("id",worksheet.id).select("id").single())}
export async function updatePatientWorksheetHomeAssignment(client:SupabaseClient,userId:string,id:string,assignedHomeAt:string|null,updatedAt:string){check(await client.from("patient_worksheets").update({assigned_home_at:assignedHomeAt,updated_at:updatedAt}).eq("user_id",userId).eq("id",id).select("id").single())}
export async function deletePatientWorksheet(client:SupabaseClient,userId:string,id:string){check(await client.from("patient_worksheets").delete().eq("user_id",userId).eq("id",id).select("id").single())}

export const patientRow=(p:Patient,userId:string)=>({id:p.id,user_id:userId,first_name:p.firstName,last_name:p.lastName,birth_date:p.birthDate||null,phone:p.contact||null,guardian_name:p.guardian||null,school:p.school||null,school_class:p.schoolClass||null,referral_reason:p.referralReason||null,notes:p.notes||null,status:p.status,updated_at:new Date().toISOString()});
const nullableTrimmed=(value:string|undefined)=>value?.trim()||null;
const nullableTaxCode=(value:string|undefined)=>nullableTrimmed(value)?.toUpperCase()||null;
export const patientAdministrativeDetailsFromRow=(row:{patient_id:string;patient_tax_code?:string|null;patient_address?:string|null;patient_postal_code?:string|null;patient_city?:string|null;patient_province?:string|null;patient_country?:string|null;billing_subject_type:PatientAdministrativeDetails["billingSubjectType"];recipient_first_name?:string|null;recipient_last_name?:string|null;recipient_tax_code?:string|null;recipient_relationship?:string|null;recipient_address?:string|null;recipient_postal_code?:string|null;recipient_city?:string|null;recipient_province?:string|null;recipient_country?:string|null;administrative_email?:string|null;created_at:string;updated_at:string}):PatientAdministrativeDetails=>({patientId:row.patient_id,patientTaxCode:row.patient_tax_code||undefined,patientAddress:row.patient_address||undefined,patientPostalCode:row.patient_postal_code||undefined,patientCity:row.patient_city||undefined,patientProvince:row.patient_province||undefined,patientCountry:row.patient_country||undefined,billingSubjectType:row.billing_subject_type,recipientFirstName:row.recipient_first_name||undefined,recipientLastName:row.recipient_last_name||undefined,recipientTaxCode:row.recipient_tax_code||undefined,recipientRelationship:row.recipient_relationship||undefined,recipientAddress:row.recipient_address||undefined,recipientPostalCode:row.recipient_postal_code||undefined,recipientCity:row.recipient_city||undefined,recipientProvince:row.recipient_province||undefined,recipientCountry:row.recipient_country||undefined,administrativeEmail:row.administrative_email||undefined,createdAt:row.created_at,updatedAt:row.updated_at});
export const patientAdministrativeDetailsRow=(details:PatientAdministrativeDetails,userId:string)=>({user_id:userId,patient_id:details.patientId,patient_tax_code:nullableTaxCode(details.patientTaxCode),patient_address:nullableTrimmed(details.patientAddress),patient_postal_code:nullableTrimmed(details.patientPostalCode),patient_city:nullableTrimmed(details.patientCity),patient_province:nullableTrimmed(details.patientProvince),patient_country:nullableTrimmed(details.patientCountry),billing_subject_type:details.billingSubjectType,recipient_first_name:nullableTrimmed(details.recipientFirstName),recipient_last_name:nullableTrimmed(details.recipientLastName),recipient_tax_code:nullableTaxCode(details.recipientTaxCode),recipient_relationship:nullableTrimmed(details.recipientRelationship),recipient_address:nullableTrimmed(details.recipientAddress),recipient_postal_code:nullableTrimmed(details.recipientPostalCode),recipient_city:nullableTrimmed(details.recipientCity),recipient_province:nullableTrimmed(details.recipientProvince),recipient_country:nullableTrimmed(details.recipientCountry),administrative_email:nullableTrimmed(details.administrativeEmail),updated_at:new Date().toISOString()});
export async function savePatientAdministrativeDetails(client:SupabaseClient,userId:string,details:PatientAdministrativeDetails){check(await client.from("patient_administrative_details").upsert(patientAdministrativeDetailsRow(details,userId)).select("patient_id").single())}
export async function deletePatientAdministrativeDetails(client:SupabaseClient,userId:string,patientId:string){check(await client.from("patient_administrative_details").delete().eq("user_id",userId).eq("patient_id",patientId).select("patient_id").single())}
export const professionalDocumentDetailsFromRow=(row:{user_id:string;tax_code?:string|null;vat_number?:string|null;address?:string|null;postal_code?:string|null;city?:string|null;province?:string|null;country?:string|null;created_at:string;updated_at:string}):ProfessionalDocumentDetails=>({userId:row.user_id,taxCode:row.tax_code||undefined,vatNumber:row.vat_number||undefined,address:row.address||undefined,postalCode:row.postal_code||undefined,city:row.city||undefined,province:row.province||undefined,country:row.country||undefined,createdAt:row.created_at,updatedAt:row.updated_at});
export const professionalDocumentDetailsRow=(details:ProfessionalDocumentDetails,userId:string)=>({user_id:userId,tax_code:nullableTaxCode(details.taxCode),vat_number:nullableTaxCode(details.vatNumber),address:nullableTrimmed(details.address),postal_code:nullableTrimmed(details.postalCode),city:nullableTrimmed(details.city),province:nullableTrimmed(details.province),country:nullableTrimmed(details.country),updated_at:new Date().toISOString()});
export async function saveProfessionalDocumentDetails(client:SupabaseClient,userId:string,details:ProfessionalDocumentDetails){check(await client.from("professional_document_details").upsert(professionalDocumentDetailsRow(details,userId)).select("user_id").single())}
export async function deleteProfessionalDocumentDetails(client:SupabaseClient,userId:string){check(await client.from("professional_document_details").delete().eq("user_id",userId).select("user_id").single())}
export const economicDocumentFromRow=(row:{id:string;patient_id:string;document_type:EconomicDocument["documentType"];status:EconomicDocument["status"];sequence_number?:number|null;number_year?:number|null;document_number?:string|null;issue_date?:string|null;professional_snapshot:Record<string,unknown>;recipient_snapshot:Record<string,unknown>;subtotal_cents:number;total_cents:number;currency_code:string;notes?:string|null;logo_included:boolean;logo_snapshot_path?:string|null;pdf_storage_path?:string|null;render_template_version:number;issued_at?:string|null;voided_at?:string|null;void_reason?:string|null;created_at:string;updated_at:string}):EconomicDocument=>({id:row.id,patientId:row.patient_id,documentType:row.document_type,status:row.status,sequenceNumber:row.sequence_number??undefined,numberYear:row.number_year??undefined,documentNumber:row.document_number||undefined,issueDate:row.issue_date||undefined,professionalSnapshot:row.professional_snapshot||{},recipientSnapshot:row.recipient_snapshot||{},subtotalCents:row.subtotal_cents,totalCents:row.total_cents,currencyCode:row.currency_code,notes:row.notes||"",logoIncluded:row.logo_included,logoSnapshotPath:row.logo_snapshot_path||undefined,pdfStoragePath:row.pdf_storage_path||undefined,renderTemplateVersion:row.render_template_version,issuedAt:row.issued_at||undefined,voidedAt:row.voided_at||undefined,voidReason:row.void_reason||undefined,createdAt:row.created_at,updatedAt:row.updated_at});
export const economicDocumentRow=(document:EconomicDocument,userId:string)=>({id:document.id,user_id:userId,patient_id:document.patientId,document_type:document.documentType,status:document.status,sequence_number:document.sequenceNumber??null,number_year:document.numberYear??null,document_number:document.documentNumber??null,issue_date:document.issueDate??null,professional_snapshot:document.professionalSnapshot,recipient_snapshot:document.recipientSnapshot,subtotal_cents:document.subtotalCents,total_cents:document.totalCents,currency_code:document.currencyCode,notes:nullableTrimmed(document.notes),logo_included:document.logoIncluded,logo_snapshot_path:document.logoSnapshotPath??null,pdf_storage_path:document.pdfStoragePath??null,render_template_version:document.renderTemplateVersion,issued_at:document.issuedAt??null,voided_at:document.voidedAt??null,void_reason:document.voidReason??null,updated_at:new Date().toISOString()});
export const economicDocumentLineFromRow=(row:{id:string;patient_id:string;document_id:string;session_id?:string|null;service_id?:string|null;service_name_snapshot?:string|null;service_date_snapshot?:string|null;description_snapshot:string;quantity:number;unit_amount_cents:number;line_total_cents:number;position:number;created_at:string;updated_at:string}):EconomicDocumentLine=>({id:row.id,patientId:row.patient_id,documentId:row.document_id,sessionId:row.session_id||undefined,serviceId:row.service_id||undefined,serviceNameSnapshot:row.service_name_snapshot||undefined,serviceDateSnapshot:row.service_date_snapshot||undefined,descriptionSnapshot:row.description_snapshot,quantity:row.quantity,unitAmountCents:row.unit_amount_cents,lineTotalCents:row.line_total_cents,position:row.position,createdAt:row.created_at,updatedAt:row.updated_at});
export const economicDocumentLineRow=(line:EconomicDocumentLine,userId:string)=>({id:line.id,user_id:userId,patient_id:line.patientId,document_id:line.documentId,session_id:line.sessionId??null,service_id:line.serviceId??null,service_name_snapshot:nullableTrimmed(line.serviceNameSnapshot),service_date_snapshot:line.serviceDateSnapshot??null,description_snapshot:line.descriptionSnapshot.trim(),quantity:line.quantity,unit_amount_cents:line.unitAmountCents,line_total_cents:line.lineTotalCents,position:line.position,updated_at:new Date().toISOString()});
export async function saveEconomicDocumentDraft(client:SupabaseClient,userId:string,document:EconomicDocument){if(document.status!=="draft")throw new Error("economic_document_draft_required");check(await client.from("economic_documents").upsert(economicDocumentRow(document,userId)).select("id").single())}
export async function deleteEconomicDocumentDraft(client:SupabaseClient,userId:string,id:string){check(await client.from("economic_documents").delete().eq("id",id).eq("user_id",userId).select("id").single())}
export async function saveEconomicDocumentLineDraft(client:SupabaseClient,userId:string,line:EconomicDocumentLine){if(!line.descriptionSnapshot.trim()||!Number.isInteger(line.quantity)||line.quantity<=0||!Number.isInteger(line.unitAmountCents)||line.unitAmountCents<0||line.lineTotalCents!==line.quantity*line.unitAmountCents)throw new Error("economic_document_line_invalid");check(await client.from("economic_document_lines").upsert(economicDocumentLineRow(line,userId)).select("id").single())}
export async function deleteEconomicDocumentLineDraft(client:SupabaseClient,userId:string,id:string){check(await client.from("economic_document_lines").delete().eq("id",id).eq("user_id",userId).select("id").single())}
export const appointmentFromRow=(a:{id:string;patient_id:string;starts_at:string;duration_minutes:number;type:Appointment["type"];notes?:string|null;recurrence_series_id?:string|null;location_id?:string|null;service_id?:string|null;location_name_snapshot?:string|null;service_name_snapshot?:string|null;effective_price_cents?:number|null;created_at:string}):Appointment=>{const d=splitDate(a.starts_at);return {id:a.id,patientId:a.patient_id,date:d.date,time:d.time,duration:a.duration_minutes,type:a.type,notes:a.notes||"",recurrenceSeriesId:a.recurrence_series_id||undefined,locationId:a.location_id||undefined,serviceId:a.service_id||undefined,locationNameSnapshot:a.location_name_snapshot||undefined,serviceNameSnapshot:a.service_name_snapshot||undefined,effectivePriceCents:a.effective_price_cents??undefined,createdAt:a.created_at}};
export const appointmentRow=(a:Appointment,userId:string)=>({id:a.id,user_id:userId,patient_id:a.patientId,starts_at:joinDate(a.date,a.time),duration_minutes:a.duration,type:a.type,notes:a.notes||null,recurrence_series_id:a.recurrenceSeriesId||null,location_id:a.locationId||null,service_id:a.serviceId||null,location_name_snapshot:a.locationNameSnapshot||null,service_name_snapshot:a.serviceNameSnapshot||null,effective_price_cents:a.effectivePriceCents??null,updated_at:new Date().toISOString()});
export const appointmentLocationFromRow=(row:{id:string;name:string;color:string;address?:string|null;city?:string|null;is_active:boolean;display_order:number;created_at:string;updated_at:string}):AppointmentLocation=>({id:row.id,name:row.name,color:row.color,address:row.address||"",city:row.city||"",isActive:row.is_active,displayOrder:row.display_order,createdAt:row.created_at,updatedAt:row.updated_at});
export const appointmentLocationRow=(location:AppointmentLocation,userId:string)=>({id:location.id,user_id:userId,name:location.name.trim(),color:location.color,address:location.address.trim()||null,city:location.city.trim()||null,is_active:location.isActive,display_order:location.displayOrder,created_at:location.createdAt,updated_at:location.updatedAt});
export const appointmentServiceFromRow=(row:{id:string;name:string;description?:string|null;default_duration_minutes:number;default_price_cents?:number|null;color?:string|null;is_active:boolean;display_order:number;created_at:string;updated_at:string}):AppointmentService=>({id:row.id,name:row.name,description:row.description||"",defaultDurationMinutes:row.default_duration_minutes,defaultPriceCents:row.default_price_cents??undefined,color:row.color??undefined,isActive:row.is_active,displayOrder:row.display_order,createdAt:row.created_at,updatedAt:row.updated_at});
export const appointmentServiceRow=(service:AppointmentService,userId:string)=>({id:service.id,user_id:userId,name:service.name.trim(),description:service.description.trim()||null,default_duration_minutes:service.defaultDurationMinutes,default_price_cents:service.defaultPriceCents??null,color:service.color??null,is_active:service.isActive,display_order:service.displayOrder,created_at:service.createdAt,updated_at:service.updatedAt});
export async function saveAppointmentLocation(client:SupabaseClient,userId:string,location:AppointmentLocation){check(await client.from("appointment_locations").upsert(appointmentLocationRow(location,userId)).select("id").single())}
export async function deleteAppointmentLocation(client:SupabaseClient,userId:string,id:string){check(await client.from("appointment_locations").delete().eq("id",id).eq("user_id",userId).select("id").single())}
export async function saveAppointmentService(client:SupabaseClient,userId:string,service:AppointmentService){check(await client.from("appointment_services").upsert(appointmentServiceRow(service,userId)).select("id").single())}
export async function deleteAppointmentService(client:SupabaseClient,userId:string,id:string){check(await client.from("appointment_services").delete().eq("id",id).eq("user_id",userId).select("id").single())}
export const sessionFromRow=(s:{id:string;patient_id:string;appointment_id?:string|null;service_id?:string|null;service_name_snapshot?:string|null;effective_price_cents?:number|null;occurred_at:string;duration_minutes?:number|null;activities?:string|null;patient_response?:string|null;help_level?:string|null;result?:string|null;next_session_plan?:string|null;homework?:string|null;notes?:string|null;created_at:string},goalIds:string[]=[],materialIds:string[]=[]):Session=>({id:s.id,patientId:s.patient_id,appointmentId:s.appointment_id||undefined,serviceId:s.service_id||undefined,serviceNameSnapshot:s.service_name_snapshot||undefined,effectivePriceCents:s.effective_price_cents??undefined,date:splitDate(s.occurred_at).date,duration:s.duration_minutes||45,goalIds,activities:s.activities||"",response:s.patient_response||"",helpLevel:s.help_level||"",result:s.result||"",nextPlan:s.next_session_plan||"",homework:s.homework||"",notes:s.notes||"",materialIds,createdAt:s.created_at});
export const sessionRow=(s:Session,userId:string)=>({id:s.id,user_id:userId,patient_id:s.patientId,appointment_id:s.appointmentId||null,service_id:s.serviceId||null,service_name_snapshot:s.serviceNameSnapshot||null,effective_price_cents:s.effectivePriceCents??null,occurred_at:joinDate(s.date,"12:00"),duration_minutes:s.duration,activities:s.activities||null,patient_response:s.response||null,help_level:s.helpLevel||null,result:s.result||null,next_session_plan:s.nextPlan||null,homework:s.homework||null,notes:s.notes||null,updated_at:new Date().toISOString()});
export const paymentFromRow=(row:{id:string;patient_id:string;amount_cents:number;paid_at:string;method:Payment["method"];note?:string|null;status:Payment["status"];voided_at?:string|null;created_at:string;updated_at:string}):Payment=>({id:row.id,patientId:row.patient_id,amountCents:row.amount_cents,paidAt:row.paid_at,method:row.method,note:row.note||"",status:row.status,voidedAt:row.voided_at||undefined,createdAt:row.created_at,updatedAt:row.updated_at});
export const paymentAllocationFromRow=(row:{patient_id:string;payment_id:string;session_id:string;amount_cents:number;created_at:string}):PaymentAllocation=>({patientId:row.patient_id,paymentId:row.payment_id,sessionId:row.session_id,amountCents:row.amount_cents,createdAt:row.created_at});
export async function createPayment(client:SupabaseClient,input:CreatePaymentInput){check(await client.rpc("create_economic_payment",{p_payment_id:input.id,p_patient_id:input.patientId,p_amount_cents:input.amountCents,p_paid_at:input.paidAt,p_method:input.method,p_note:input.note?.trim()||null,p_allocations:input.allocations}))}
export async function voidPayment(client:SupabaseClient,paymentId:string){check(await client.rpc("void_economic_payment",{p_payment_id:paymentId}))}
export const goalFromRow=(g:{id:string;patient_id:string;clinical_pathway_id?:string|null;title:string;description?:string|null;priority?:number|null;status:string;progress?:number|null;created_at:string}):Goal=>({id:g.id,patientId:g.patient_id,clinicalPathwayId:g.clinical_pathway_id||undefined,title:g.title,description:g.description||"",priority:g.priority||2,status:g.status,progress:g.progress||0,createdAt:g.created_at});
export const goalRow=(g:Goal,userId:string)=>({id:g.id,user_id:userId,patient_id:g.patientId,clinical_pathway_id:g.clinicalPathwayId||null,title:g.title,description:g.description||null,priority:g.priority,status:g.status,progress:g.progress,updated_at:new Date().toISOString()});
export const profileRow=(p:Profile,userId:string)=>({id:userId,full_name:`${p.firstName} ${p.lastName}`.trim(),first_name:p.firstName,last_name:p.lastName,profession:p.profession,email:p.email,studio:p.studio,calendar_color_mode:p.calendarColorMode,onboarding_completed_at:p.onboardingCompletedAt??null,updated_at:new Date().toISOString()});
export const materialRow=(m:Material,userId:string)=>({id:m.id,user_id:userId,title:m.title,description:m.description||null,category:m.category,tags:m.tags,file_name:m.fileName||null,storage_path:m.storagePath||null,mime_type:m.mimeType||null,file_size:m.size||null,external_url:m.externalUrl||null,is_favorite:m.favorite,updated_at:new Date().toISOString()});
export async function replaceLinks(client:SupabaseClient,table:"patient_materials"|"session_materials",ownerKey:"material_id"|"session_id",ownerId:string,linkKey:"patient_id"|"material_id",ids:string[]){check(await client.from(table).delete().eq(ownerKey,ownerId));if(ids.length)check(await client.from(table).insert(ids.map(id=>({[ownerKey]:ownerId,[linkKey]:id}))));}
export async function signedFileBlob(client:SupabaseClient,path:string){const result=check(await client.storage.from("therapy-materials").createSignedUrl(path,300));if(!result.data)throw new Error("Impossibile creare il link sicuro al file");const response=await fetch(result.data.signedUrl);if(!response.ok)throw new Error("Impossibile aprire il file privato");return response.blob();}
